### ISSUE TITLE
word birth analysis

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#10]
This is a somewhat crazy idea from discussion with Dan. 

Part 1: create predictive model of "word birth" age - that is, based on log freq, MLU of word, number of phones, lexical category, predict the probability of a child at a particular age knowing it (proportional hazard model)? 

Part 2: Then use this as the baseline model and add predictors like conditional dependence in acquisition (MI between words) - e.g. knowing "think" implies you know "believe"? 

Part 3: Could extract the conditional dependency matrix and use this as the basis for various cluster analyses.

**Comment by mikabr** [comment]
Now that we have AoA estimates, we could actually do something like this if we wanted to.
