### ISSUE TITLE
disclaimer upgrade

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#102]
- [x] make the "more details" link blue on norm site
- [x] make a scrolly down link in the top text (blue also)

**Comment by mcfrank** [comment]
also make a static disclaimers page (perhaps a blogpost?) and link to this in the paper.  especially note:

* interpret proportions not raw scores
* don't assume translation equivalence
* don't assume population equivalence

**Comment by mcfrank** [comment]
also fix: 
- [ ] gcrq is actually quantRegGrowth

**Comment by mikabr** [comment]
up now. look good?

**Comment by dyurovsky** [comment]
See below links from the headers don't seem to take me to the place in-page?

Dan

**Comment by mikabr** [comment]
The link works fine [on a webpage](http://54.149.39.46:3838/item_trajectories/) but seems to be failing because it's inside an iframe. Might be a hassle to work around, will investigate...

**Comment by mcfrank** [comment]
also - on top text: "see below for more details and an important disclaimer about clinical usage."

**Comment by mcfrank** [comment]
Take out link on disclaimer.
