### ISSUE TITLE
"data filter" popup menu

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#106]
as we include more diverse and heterogeneous data in wordbank (e.g., multilinguals, longitudinal, developmental disorders, etc.) we should make a popup that allows filtering of special populations for every report. then that can come with defaults, e.g. "no multi-linguals, no DD, yes to longitudinal, etc." but can be checked/unchecked. 

Also this can finally instantiate @vmarchman's long-desired "recover 2007 norms" button, which I think would be a very good feature for many users.

**Comment by mikabr** [comment]
depends on #24

**Comment by mcfrank** [comment]
duplicated #124
