### ISSUE TITLE
make reports show a loading screen while they initially load

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#11]
No idea how to do this, though.

**Comment by mikabr** [comment]
Left shiny-busy alone, did it with jQuery. The loading screen now displays until the iframe containing the report has loaded. It seems pretty good, but after that loading period there's still a delay as shiny populates all the selectize inputs. There might be a better way of using selectize that results in a shorter delay, or shiny-busy might be on during that period, or we could decide this delay is fine.
