### ISSUE TITLE
text wrap for reports

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#123]
if you zoom in chrome, nothing good happens to instructions. 

![2016-02-01-04-29-24-wordbank-analyses](https://cloud.githubusercontent.com/assets/1158807/12728011/9ff84912-c8d4-11e5-88fd-07a967bd621e.png)

**Comment by mikabr** [comment]
The instruction are within the shiny apps, which is put into this page through an iframe, so it has no idea how wide your viewing window is. We could take the instructions out of the app put them directly into the page? Not sure how to fix this otherwise.
