### ISSUE TITLE
unilemmas report

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#125]
this could be one tool to browse mappings across languages (select item, show curves for all languages)

**Comment by mikabr** [comment]
This mostly [already exists](https://mikabr.shinyapps.io/uni_lemma), but works off of a static csv of the data because the aoa estimation code takes a while to run.

**Comment by mikabr** [comment]
IIRC the part that takes up the most time isn't model fitting, it's the logic to combine items into uni_lemmas (if a kid knows any of the words that map to a given uni_lemma, give them credit for that uni_lemma). That step could probably be done in a better/faster way.

**Comment by mcfrank** [comment]
That looks great, though it also shows some real issues in the wordlist, I
think...

Mike
