### ISSUE TITLE
import Slovak data

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#130]

**Comment by mikabr** [comment]
All the prep work for this is done, but I haven't run it on the server because there are a lot mysterious values in the data -- for example, questions with 3 values (understands, understands and produces, neither) are coded with 4 values (0,1,2,3). Even worse, there's a bunch of weird values like "23", which might mean something (maybe they were indicating something between a 2 and a 3?) or might be garbled data (maybe they're supposed to be in two separate columns and values are shifted over?). Anyway, things are messy enough that I don't want to actually import until we figure out more about what's going on...

**Comment by mcfrank** [comment]
Should we follow up? If you give me a few examples, I'll write back to them
and cc you, or you can just write directly if that's easier.


Mike

**Comment by mcfrank** [comment]
decision: import ONLY words, under the assumption that 0 = blank, 1 = "does not understand", 2 = "understands", 3 = "produces"
