### ISSUE TITLE
data report names

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#142]
+ "by-word (item) averages"
+ "by-child (administration) averages"
+ "full datasets by form"

**Comment by mcfrank** [comment]
consensus: check these with actual users

**Comment by mikabr** [comment]
Who should we ask for user input?

Thought: we could start a `wordbank-users` mailing list, where we can announce new features and get feedback on questions. Might not be enough of a community for it yet, but it could help grow the community?

**Comment by mcfrank** [comment]
mailing list seems like a great idea...

Mike

**Comment by mikabr** [comment]
I put in a request for the mailing list, and in the mean time changed the app names to something that made sense to me.
