### ISSUE TITLE
stick attribution on gender diffs

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#144]
cite and note that this is replication Erikson paper.

**Comment by mikabr** [comment]
what's the paper/citation?

**Comment by mcfrank** [comment]
Eriksson, M., Marschik, P. B., Tulviste, T., Almgren, M., Pérez Pereira,
M., Wehberg, S., … Gallego, C. (2012). Differences between girls and boys
in emerging language skills: Evidence from 10 language communities. British
Journal of Developmental Psychology 30, 326–343.

Mike
