### ISSUE TITLE
rerun data reports and cache on the dataset

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#145]
so that the "static" reports are rerendered

**Comment by mikabr** [comment]
I'm not sure if you mean have them re-render automatically every night -- our discussion the other day seemed to converge on that not being the right plan, given how heterogenous and complex they are.

**Comment by mcfrank** [comment]
Yeah, I guess so - though maybe we could make a subset live update? E.g.
migrate them into the local repo, at least the ones that are not hard core
computationally?

Mike

**Comment by dyurovsky** [comment]
Maybe momed and gender differences?

Dan

**Comment by mikabr** [comment]
gender and momed now get re-rendered automatically every night

**Comment by mikabr** [comment]
the auto rendering script works totally fine if I run it, but doesn't seem to get run by chron for some reason...
