### ISSUE TITLE
min font size on front language graphic

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#147]
Right now we can't see many of the smaller languages' names

**Comment by mikabr** [comment]
The graphic is now over kids rather than administrations, which makes is broadly look better, but BSL is now just completely invisible... we could just make the graphic exclude any language with too-small sample sizes?

**Comment by mcfrank** [comment]
Probably we should quit while we're ahead… Looks better in any case. We
could try logarithms though?
