### ISSUE TITLE
hard-coded instrument selectors

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#162]
were crashing the vocab_norms and item_trajectories reports. these are now fixed, but there is no in-database source that lets us know which instruments have comprehension data - for example, ASL currently has a form called "FormA" that does, but "FormC" for example doesn't. we should probably eventually put this information in the instruments table.

**Comment by mikabr** [comment]
doesn't the measure selector infer this from the data?

**Comment by mcfrank** [comment]
not currently - it was hard-coded, at least in vocab_norms

**Comment by mikabr** [comment]
ah ok – in a given form different section have different sets of options, but the options for the words could be put in the instruments table
