### ISSUE TITLE
educational materials

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#166]
create a tab for teaching with wordbank. this will require some thought, but I think will be fun and useful. 

I thought we had a doc with some ideas but I've lost track of it. 

materials from Caitlin Fausey:

slides: https://docs.google.com/presentation/d/1VnhKdCBOzgxaaCwm3CsTtF-Cu3gfsl7Kgz1CwQ5c_SE/edit?usp=sharing

assignment: https://docs.google.com/document/d/1UOHuF26t19HLPswsVm46ivA7nS98Z3G9ht9GwCtJYJ0/edit?usp=sharing

**Comment by mikabr** [comment]
@mcfrank could be linked to on the documentation page? #244
