### ISSUE TITLE
vocab norms: model fit warning doesn't go away

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#170]

**Comment by daniellekellier** [comment]
Are you talking about the "The current model does not fit well to this dataset" warning?

**Comment by mikabr** [comment]
yes

**Comment by daniellekellier** [comment]
Could you tell me where exactly this bug is happening? I've been playing with the app on wordbank.edu and the warning is going away for me.

**Comment by mikabr** [comment]
hmm yeah, it seems to mostly go away – I can't reproduce what circumstances go it into that weird state
