### ISSUE TITLE
Vocab Norms App fails to model English (American) - W&G - comprehension

### ISSUE THREAD

**Issue by daniellekellier** [langcog/wordbank#173]
![image](https://user-images.githubusercontent.com/19960439/30555420-5c35433a-9c5c-11e7-8cec-e7dd91abe013.png)

`fit_curves()` function fails specifically at line 218
`models <- data() %>%
    group_by(demo) %>%
    do(model = gcrq(vocab ~ ps(age, monotone = 1, lambda = 1000),
        data = ., tau = input_quantiles()))`

'None' Split Variable is the only one that fails
For Quantiles 'Standard' and 'Quartiles' fail

**Comment by daniellekellier** [comment]
Problem was related to the actual SQL data. Exact R package versions did not generate the issue. Resetting the 'English (American) Words & Gestures' instrument and re-importing related study data fixed the issue.

**Comment by mcfrank** [comment]
Huh, ok, glad that this is resolved!
