### ISSUE TITLE
viewing multiple word item trajectories

### ISSUE THREAD

**Issue by benpeloquin7** [langcog/wordbank#174]
Default view of item [trajectories](http://wordbank.stanford.edu/analyses?name=item_trajectories) plots AoA for "baa baa". Adding another word to the `Words` input field does not plot (however the table view looks good). Running in chrome browser.
<img width="859" alt="screen shot 2017-10-02 at 4 52 00 pm" src="https://user-images.githubusercontent.com/2654729/31104601-bffd2d92-a792-11e7-813c-4e4dba93f772.png">.

**Comment by daniellekellier** [comment]
This has been fixed!
