### ISSUE TITLE
Update unilemmas

### ISSUE THREAD

**Issue by daniellekellier** [langcog/wordbank#177]
Add unilemmas for the following forms

- [x] American Sign Language (FormA, FormBOne, FormBTwo, FormC)
- [x] British Sign Language (WG)
- [x] Cantonese (WS)
- [ ] Croatian (WS)
- [x] Czech (WS)
- [ ] Danish (WS)
- [x] English, Australian (WS)
- [x] English, British (Oxford CDI, TEDS Twos, TEDS, Threes)
- [x] French, Quebecois (WS)
- [x] French, French (WG, WS)
- [x] German (WS)
- [x] Greek, Cypriot (WS)
- [x] Hebrew (WS) 
- [ ] Italian (WS)
- [ ] Kigiriama (WG, WS)
- [x] Kiswahili (WG, WS)
- [x] Latvian (WG)
- [ ] Latvian (WS)
- [ ] Mandarin (WS)
- [x] Mandarin, Taiwanese (WG)
- [ ] Mandarin, Taiwanese (WS)
- [x] Norwegian (WS)
- [x] Portuguese, European (WG)
- [ ] Portuguese, European (WS)
- [x] Slovak (WG, WS)
- [x] Spanish, European (WG)
- [ ] Spanish, European (WS)
- [x] Spanish, Mexican (WG, WS)
- [ ] Swedish (WS)
- [ ] Turkish (WS)

**Comment by kachergis** [comment]
I'd be happy to find help for these, but are these up-to-date?

**Comment by kachergis** [comment]
get_crossling_items() returns 1380 unilemmas, and I guess we need to check which of those are NA for each language. Just looking at a couple items, the above list is out-of-date (and incorrect? or at least Czech, Cantonese, and others don't appear on this list -- but maybe they don't have 'hat' or 'nose'?):
unique languages in get_crossling_data(uni_lemmas = c("hat", "nose"))
[1] "British Sign Language" "Croatian"              "Danish"                "English (American)"   
 [5] "French (French)"       "French (Quebecois)"    "Hebrew"                "Italian"              
 [9] "Kiswahili"             "Korean"                "Norwegian"             "Russian"              
[13] "Slovak"                "Spanish (Mexican)"     "Swedish"               "Turkish"

**Comment by mcfrank** [comment]
@kachergis

**Comment by kachergis** [comment]
added Latvian WG, Mandarin Taiwanese WG, and Spanish European WG uni_lemmas, updated (added more and fixed a few) Korean WG and Mandarin IC Beijing uni_lemmas

**Comment by HenryMehta** [comment]
@kachergis has this been merged into master and do I need to merge it into the Py38 version?  If so what was the merge so I know what I'm looking to pull back

**Comment by kachergis** [comment]
@HenryMehta I made the PR a few weeks back but only just merged it now: https://github.com/langcog/wordbank/commit/829b99be0164a04965111ec5865d3802b10538f7
(I assume it didn't make the Py38 version, then)
Mika said you likely know how to update these tables, but let her/I know if you don't -- thank you!!!

**Comment by HenryMehta** [comment]
@kachergis I would appreciate some confirmation on how to merge them because I've done it by rebuilding the whole database and I don't want to do that again.  I also want to ensure things don't get double counted which has happened, so can you give specific instructions about exactly what to do - thanks

**Comment by HenryMehta** [comment]
@kachergis Hi George, I really need some direction here because I don't know what you've changed and how I migrate it - I don't see any differences in the numbers and I could just merge the branches but if I don't know what you've done or what I'm then meant to do I won't necessarily apply it properly
Thanks

**Comment by kachergis** [comment]
Hi @HenryMehta -- sorry for the slow reply: I've been traveling. I've
updated a few languages' uni_lemma columns for the WG forms, but more are
in progress. I've briefly discussed with Mika how to remove and then
reingest the updated instruments, so I don't think a full database rebuild
will be needed -- but let me get back to you once we're done updating.

**Comment by mcfrank** [comment]
Instructions for emailing new folks: ```Hi there, thanks very much for agreeing to help us with our translation task! 

Instructions

We are trying to get good translations of different lists of words in many different languages into the same set of "universal" concepts - here expressed in English. A list of these concepts are on the "BANK" tab. So, for example, we want to map "perro" in Spanish onto "dog" in English. Of course, exact translation is really hard, and we're just trying to do our best (with your help). 

To do the task, navigate to your language, and then, for each word on the list, take a look at the translations that are given. We're looking for the best English translation. These are words that are among the first words that children learn, so your translation should be closest to the meaning of the word as it would be used by a young child (say, under 3 years old).
If the translation is good, just put a 1 in the "is translation good?" column.
If the translation is bad, put a 0, and put an alternative in the "alternative translation column."
For cases when there are two equally good English words, put both.
If you don't think there is a good translation into a reasonable English word that a kid might know, you can leave the alternative translation blank, and write a note. 
Also feel free to write notes about other words to let us know your thoughts behind your decision or if there is anything else we should consider.
Here's the spreadsheet we're working from. Your language should be on one of the tabs on the bottom. 

https://docs.google.com/spreadsheets/d/15RMcFOURhtv0DxA8aBXaXExq-7qChB6EEnlh8p4V7o4/edit#gid=1108769780

Let me know if you have any other questions. And when you're done, just respond to this email and we'll get you an amazon gift card in thanks for your time. 
```

**Comment by kachergis** [comment]
check current coverage

```{r}
instr <- wordbankr::get_instruments() %>% 
  arrange(desc(unilemma_coverage))
```
