### ISSUE TITLE
Add Persian Data

### ISSUE THREAD

**Issue by daniellekellier** [langcog/wordbank#185]

**Comment by mcfrank** [comment]
```
Two zip files are attached including:
1.MCDI-I-infants form: the correct SPSS file (115 children). It contains children's ages. (The previous file was for students' statistical training and was wrong!) + the most recent MCDI-WG form. 

2. MCDI-II-toddler form: the previous SPSS file of toddlers (50 children). It contains children's ages. + the old MCDI-W form which has been published in a child assessment battery called PANA and can be purchased from the publisher.

Regarding the names of items, I really would have liked to complete the list but unfortunately it takes time! I hope your Persian-speaking colleague can help you with the corresponding names of each variable of SPSS data with the proper name in the form. 
However, here is a guide to the name of items: each vocabulary category in the form starts with an alphabet name in SPSS file, so that you will have, for instance, B1, B2, B3, B4 ... up to B28 for category of "phrases" in infants' form. Similarly, you will have A1 to A15 for category of "animal and environmental sounds" in toddler's form and so on.

I will be so glad to contribute with any further developing project of MCDI. So, please let me know if I can be of any help in this regard.

Best wishes
Yalda
```

[Archive.zip](https://github.com/langcog/wordbank/files/6280010/Archive.zip)

**Comment by alv1nn** [comment]
Note: pending instrument specification

**Comment by mcfrank** [comment]
Citation: 



Kazemi, Y., Afsharian, E., Mirzaei, B., Baghbani, M., Sademinejad, M., & Gheleyempour, L. (2007). Children's communication checklist: The study of persian children. Iranian Journal of Research in Rehabilitation Sciences, 2(3), 1-5.

**Comment by alvinwmtan** [comment]
@HenryMehta cleaned data files:
[[Persian_WG].csv](https://github.com/langcog/wordbank/files/8734676/Persian_WG.csv)
[PersianWG_Kazemi_data.csv](https://github.com/langcog/wordbank/files/8734677/PersianWG_Kazemi_data.csv)
[PersianWG_Kazemi_fields.csv](https://github.com/langcog/wordbank/files/8734678/PersianWG_Kazemi_fields.csv)
[PersianWG_Kazemi_values.csv](https://github.com/langcog/wordbank/files/8734679/PersianWG_Kazemi_values.csv)

[[Persian_WS].csv](https://github.com/langcog/wordbank/files/8734680/Persian_WS.csv)
[PersianWS_Kazemi_data.csv](https://github.com/langcog/wordbank/files/8734681/PersianWS_Kazemi_data.csv)
[PersianWS_Kazemi_fields.csv](https://github.com/langcog/wordbank/files/8734682/PersianWS_Kazemi_fields.csv)
[PersianWS_Kazemi_values.csv](https://github.com/langcog/wordbank/files/8734684/PersianWS_Kazemi_values.csv)

Note: WS verb items (prefixed `f(el)` or `felekomaki` in the data file) *do not* match the items on the provided form, thus we have excluded these data.

**Comment by HenryMehta** [comment]
**Persian WS** 
There is a data value of 10 in column h.e8.  I added `word,,10` to the `_values` file to manage it.  If you want produces, let me know.

Administration id 46 has no age so I set it to the file average of 24.64

**Persian WG**
There is a data value of 10 in column e12.  I added `word,,10` to the `_values` file to manage it.  If you want produces, let me know.

There is a data value of 11 in column o1.  I added `word,,10` to the `_values` file to manage it.  If you want produces, let me know.

The `[Persian_WG].csv` file stops at `item_400`, so I've deleted `item_401` through `item_433` from the `_fields` file.

Otherwise, all loaded

**Comment by alvinwmtan** [comment]
@HenryMehta thanks for catching the erroneous values; `word,,10` is correct.

Also, sorry about the misspecification in Persian_WG; I'll upload a new form spec with the corrected values (it should have items all through `item_433`, but I accidentally left these out of the form)

**Comment by alvinwmtan** [comment]
@HenryMehta Here is the corrected form file and the new values file (to cover the new items). Data and fields files should be the same as before. 
[[Persian_WG].csv](https://github.com/langcog/wordbank/files/8741207/Persian_WG.csv)
[PersianWG_Kazemi_values.csv](https://github.com/langcog/wordbank/files/8741216/PersianWG_Kazemi_values.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan Loaded

**Comment by alvinwmtan** [comment]
@HenryMehta pulled from R—looks good to go!
