### ISSUE TITLE
kiswahili/kigiriama import

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#188]
It seems likely that something has gone wrong with the WG import and that production/comprehension are flipped. 1 is currently listed as produces and 2 as comprehends - I think this is likely a reversal and is leading to some bad behavior of the data? @daniellekellier could you investigate? I think you wrangled these initially. thanks!

**Comment by daniellekellier** [comment]
Fixed! I looked at the original data sent over and it was just because I flipped the values for understands/produces. It should look better now!

**Comment by mcfrank** [comment]
yay!
