### ISSUE TITLE
add eric walle data!

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#192]
[Walle Lab - MCDI - for Mike Frank.xlsx](https://github.com/langcog/wordbank/files/2670642/Walle.Lab.-.MCDI.-.for.Mike.Frank.xlsx)

**Comment by HenryMehta** [comment]
I believe this is ready to put up.  I've merged the first 2 sheets as 1 load (English_WG) and the last 3 sheets as 1 load (English_WS).

**Comment by alvinwmtan** [comment]
Hi @HenryMehta, could I check if this is ready to load / has been loaded?

**Comment by HenryMehta** [comment]
@alvinwmtan No, I did the work to implement it a couple of years ago, but no one checked or tested it and it looks like the data is gone - I cannot find it in any branch on GitHub

**Comment by mcfrank** [comment]
holding off because it's short forms

**Comment by alvinwmtan** [comment]
@HenryMehta cleaned files here:

[[EnglishWGShort].csv](https://github.com/langcog/wordbank/files/8971860/EnglishWGShort.csv)
[EnglishWGShort_Walle_data.csv](https://github.com/langcog/wordbank/files/8971861/EnglishWGShort_Walle_data.csv)
[EnglishWGShort_Walle_fields.csv](https://github.com/langcog/wordbank/files/8971862/EnglishWGShort_Walle_fields.csv)
[EnglishWGShort_Walle_values.csv](https://github.com/langcog/wordbank/files/8971863/EnglishWGShort_Walle_values.csv)

[[EnglishWSShort].csv](https://github.com/langcog/wordbank/files/8971864/EnglishWSShort.csv)
[EnglishWSShort_Walle_data.csv](https://github.com/langcog/wordbank/files/8971865/EnglishWSShort_Walle_data.csv)
[EnglishWSShort_Walle_fields.csv](https://github.com/langcog/wordbank/files/8971866/EnglishWSShort_Walle_fields.csv)
[EnglishWSShort_Walle_values.csv](https://github.com/langcog/wordbank/files/8971867/EnglishWSShort_Walle_values.csv)

(uses policy from [#251](https://github.com/langcog/wordbank/issues/251#issuecomment-1164916692))

**Comment by HenryMehta** [comment]
@alvinwmtan loaded, although we have a #value! error on item AE-236 column out.  I've simply deleted the value so will be null in database

**Comment by HenryMehta** [comment]
there are also 2 records with no age so I entered 19 which is the average for the dataset

**Comment by alvinwmtan** [comment]
@HenryMehta looks good from R
