### ISSUE TITLE
issue in Mandarin data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#193]
I wanted to let you all know about a possible discrepancy in the CDI data for the Words and Sentences form for Mandarin (Beijing). I've attached an excel spreadsheet to this message showing the data I'm talking about. The first tab shows the CDI W&S item data as provided by the wordbankr / wordbank website. I've highlighted several rows with definitions that appear to be repeated. I've been working with a Mandarin speaker on a project using this CDI data and he has helped me go through the Mandarin CDI manual and find the missed items. I've attached a scan of the page with the missing items marked. The second tab in the excel spreadsheet shows the corrected version of the item data. While most of the corrected items seem to more or less match the provided uni_lemma, some of them do not (in particular items 457, 458, and 534-537). For instance, item 457 (长) has a uni_lemma of 'sick', but my Mandarin speaker has translated the word as 'long'. I just wanted to bring all this to your attention in case some things were flipped around in other places.

Let me know if I can be of any assistance. Thanks for you all your work on Wordbank -- it's been a terrific resource.

Justin Kueser, M.Ed., CCC-SLP
PhD Student
Speech, Language, and Hearing Sciences
Purdue University
[CDI_page_scan_update_011419.pdf](https://github.com/langcog/wordbank/files/2885738/CDI_page_scan_update_011419.pdf)
[ws_items_wordbankr.xlsx](https://github.com/langcog/wordbank/files/2885740/ws_items_wordbankr.xlsx)

**Comment by mcfrank** [comment]
+jkueser@purdue.edu

**Comment by mcfrank** [comment]
related to #177 @kachergis

**Comment by HenryMehta** [comment]
@mcfrank @alvinwmtan 
I'm not sure I've done the right action here so please confirm.

I have updated the chinese characters within [Mandarin_Beijing_WS].csv to reflect those in the spreadsheet above for items item_442 to item_465 and items item_534 to item_541.  I have then reloaded the dataset file to reflect the changes

**Comment by alvinwmtan** [comment]
@HenryMehta we are currently updating the unilemmas, so all of the [lang_form].csv files will be changed; I will update you as soon as possible!

**Comment by alvinwmtan** [comment]
subsumed under #266
