### ISSUE TITLE
Functionality for bilinguals

### ISSUE THREAD

**Issue by kristabh** [langcog/wordbank#195]
Wish list item: Functionality for uploading data from bilinguals.  Ideally, we would be able to link data from two CDIs (one in each language) for bilingual children. And we'd need to be able to integrate info about age of acquisition of each language, and percent exposure to each language.

**Comment by mcfrank** [comment]
ok, we are working on this! @kristabh do you have item-level data that would be a good use-case for us?

@HenryMehta we are planning to move forward with this, and would love to get your help. @vmarchman will follow up. 

@mikabr I think we want to add just a "multilingual" column to the `administrations` table, right? - do you have a sense for how this should be structured?

@vmarchman @JMankewitz

**Comment by mcfrank** [comment]
@georgialoukatou

**Comment by kristabh** [comment]
Glad this is a go! We have item-level data for Words & Gestures, as well as Words and Sentences.  Bilinguals learning Quebec French and American English.

We definitely need a field for % exposure to the language of administration (if it doesn't already exist). Ideally age of acquisition as well.

**Comment by mcfrank** [comment]
@HenryMehta we are having a conversation about this and planning on working together synchronously on 4/1 at 9AM - 1PM pacific. 

we are thinking that there is a relatively unused "child" table where we could store bilingualism information and use IDs from that table to retrieve matching administrations. do you think you could take a look at this? @vmarchman or I would be happy to chat more about the requirements...

**Comment by HenryMehta** [comment]
> @HenryMehta we are having a conversation about this and planning on working together synchronously on 4/1 at 9AM - 1PM pacific.
> 
> we are thinking that there is a relatively unused "child" table where we could store bilingualism information and use IDs from that table to retrieve matching administrations. do you think you could take a look at this? @vmarchman or I would be happy to chat more about the requirements...

Yes, of course.  But you do realise that Wordbank is all written in Python 2.7 so isn't supported or certain to work on AWS servers.  Any changes without upgrading will carry more risk

**Comment by mcfrank** [comment]
ugh so we should probably upgrade? this sounds complex... @mikabr

**Comment by mikabr** [comment]
I don't have any experience with python 3 upgrades, but it sounds like
something we should potentially do anyway?

**Comment by mcfrank** [comment]
@Henry ***@***.***> I know you are off for a bit, but when you are
back, do you think you could prepare a quote for the upgrade? I agree with
Mika.

thanks!

**Comment by HenryMehta** [comment]
@mcfrank Yes, I've no problem doing the upgrade but I've only got 10-15 hours per week available at the moment (I might be able to push that to 20 sometimes).  I need to get some work done on WebCDI this week.  Would starting next week be ok and is there a timescale on this?

**Comment by mcfrank** [comment]
Hi Henry, thanks! This is a spring goal for us, we were thinking about
working on bilingual functionality on April 1. Maybe when you take a look
you can see if that feels out of reach... if so, we can move our plans back
by a few weeks.

**Comment by HenryMehta** [comment]
Hi Mike,
Sorry to be pedantic, but does spring mean March 21st (I think that is official calendar start) or before June 21st (calendar end) or something else. 

I've been trying to find historical data on how long the WebCDI upgrade took me, but I can't.  I suspect we're talk 20-30 hours for a system I knew, so I think we need to assume something similar for Wordbank which I think is less complicated.  So we're talking 2-3 weeks at 10-15 hours per week from next week.  I think if we add a couple of weeks contingency, that gives us a safe estimate

**Comment by mcfrank** [comment]
thanks Henry! so something like an estimated done date of 4/15? that would
be fine for us to schedule around.

**Comment by mcfrank** [comment]
linking this issue to us needing flags for longitudinal data and clinical data as well (#179) - all of these are things that are by-default filtered, e.g. as in the "norming data" flag. (#168)

**Comment by mcfrank** [comment]
https://docs.google.com/document/d/1dghcGe5KBculGS41Ur7VkHP63lNvJgqmpdIRxuMU4J4/edit#
