### ISSUE TITLE
Running import_datasets twice causes additional administrations

### ISSUE THREAD

**Issue by HenryMehta** [langcog/wordbank#199]
If you run a dataset twice it duplicates the administrations within the application (but doesn't seem to duplicate the children). I don't know if this causing an issue with later analysis etc but I would expect the record to be loaded only once and to be checked before trying to load.

**Comment by mikabr** [comment]
iirc the workflow is to run `reset_instrument` and then `import_datasets

**Comment by HenryMehta** [comment]
Thank you - that makes sense
