### ISSUE TITLE
consider removing scoring app

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#200]
@melsod notes some 1-2 percentile discrepancies with webcdi scoring - that's a reason to consider taking this tool down. what do you think @vmarchman?

**Comment by mcfrank** [comment]
@HenryMehta could you remove the scoring app from the Analyses page? No need to take down the shiny app yet but let's remove it. thanks!

**Comment by HenryMehta** [comment]
@mcfrank  I've removed the "Scoring Tool" from analysis page, which is what I think you want and it is ready to test

This Python38 upgrade has not touched the shiny app functionality (which is in R).  All that remains in place and is still being called as per previous version

**Comment by mcfrank** [comment]
Yup, that sounds great. Thanks.
