### ISSUE TITLE
Cantonese data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#201]
Greetings, my name is Lizz, I am a research assistant of the Education University of Hong Kong. I am writing to inquire about the way of making contribution for Wordbank with our latest research output that published in Cognition (Chen, Hui, Lee, Daniel T, Luo, Zili, Lai, Regine Y, Cheung, Hintat, and Nazzi, Thierry. "Variation in Phonological Bias: Bias for Vowels, Rather than Consonants or Tones in Lexical Processing by Cantonese-learning Toddlers." Cognition (2020): 104486. Web.)

In the research, we use the Cantonese version of the CDI (Tardiff & Fletcher, 2008) to determine the size of the children's productive vocabulary. Over 300 monolingual children's CDI data were collected, age grouped in 14, 20 and 30 months. Among them, 72 20-month-olds and 72 30-months-olds are included in the paper.

We now have the data completely coded in one single spreadsheet that are ready to be submitted. We would like to know if you have a preferred way to organize the data and if there are things we need to know regarding the submission.

Chen, H., Lee, D.T., Luo, Z., Lai, R.Y., Cheung, H., & Nazzi, T. (in press). Variation in phonological bias: Bias for vowels, rather than consonants or tones in lexical processing by Cantonese-learning toddlers. Cognition.

https://doi.org/10.1016/j.cognition.2020.104486

**Comment by mcfrank** [comment]
[CDI_for_Wordbank.csv.zip](https://github.com/langcog/wordbank/files/5783025/CDI_for_Wordbank.csv.zip)

**Comment by alvinwmtan** [comment]
files cleaned for import:
[CantoneseWS_Nazzi_data.csv](https://github.com/langcog/wordbank/files/8551429/CantoneseWS_Nazzi_data.csv)
[CantoneseWS_Nazzi_fields.csv](https://github.com/langcog/wordbank/files/8551430/CantoneseWS_Nazzi_fields.csv)
[CantoneseWS_Nazzi_values.csv](https://github.com/langcog/wordbank/files/8551431/CantoneseWS_Nazzi_values.csv)

**Comment by alvinwmtan** [comment]
@HenryMehta looks good from R!
