### ISSUE TITLE
contributors page text

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#202]
From Philip Dale: "I’ve already posted a notice on info-childes about this. Here’s a suggestion of how to handle this on your website. You could just put in a note (item #7 on your Contributors page?) that the 

```
Use of Wordbank data for the development of new CDI instruments is permitted, but must be approved by the CDI Advisory Board. Developers planning on use of Wordbank data for this purpose should see the Adaptations Guidelines on the [CDI website](https://mb-cdi.stanford.edu/adaptations.html).
```
 
(we’ll be posting newly revised guidelines in the next few days which contain the new material.)
 
Thanks for your help on this."

**Comment by mcfrank** [comment]
the text could go right below the "to contribute your data..." line at the top? #205

**Comment by HenryMehta** [comment]
@mcfrank deployed to dev environment

**Comment by mcfrank** [comment]
looks great.

**Comment by HenryMehta** [comment]
@mcfrank Can I suggest it isn't closed until it is live.  I've added it to a Project and will move it to ready for go live

**Comment by mcfrank** [comment]
point taken, thanks!
