### ISSUE TITLE
Danish and Norwegian have no blank ("") response values; only NAs

### ISSUE THREAD

**Issue by kachergis** [langcog/wordbank#204]
The unique values of the responses column for both Danish and Norwegian do not contain any blank ("") values (only "produces", "understands", and NAs).
Presumably all of the NAs should be "", unless there are some missing cells.

Reprex:

```{r}
language = "Danish" # or "Norwegian"
  d_demo <- 
    get_administration_data(language = language, form = "WG") 
  items <- get_item_data(language = language, form="WG") %>%
    filter(type=="word")
  d_long_wg <- get_instrument_data(language = language, form = "WG") %>% # 418 items
    left_join(items %>% select(-complexity_category), by="num_item_id") %>%
    mutate(produces = as.numeric(value == "produces"),
           comprehends = as.numeric(value == "understands")) %>%
    filter(type=="word")
  table(d_long_wg$value)
```

produces  understands (no '' values -- all are NA)
    51184      190974

**Comment by HenryMehta** [comment]
@kachergis I have been working on this all day trying to understand why these are coming through a null.  I think it does in all languages when there is no data_value.  So something like `word,,` or`word,xxx,` will both create null in the database but `word,,0` which give the desired result, as long as 0 is in the cell within the data file.

We have the same issue with Byres in English American

**Comment by HenryMehta** [comment]
Finally got there.  The code is written to set the value to null when the field contains the following: 'Null', '#NULL!', '', ' ', 'Missing', 'Unknown/other', '?', 'NA', '99' 

I'm guessing this was done because if a cell is empty we don't know if it is deliberately empty or the value is missing.

What would you like me to do?

**Comment by alvinwmtan** [comment]
@HenryMehta this appears to not be fixed? I'm not sure how to go about fixing it. And do you know if this affects all languages that have `word,,` in their `_values.csv` file? (I believe that quite a few have this.)

**Comment by HenryMehta** [comment]
@alvinwmtan 
Not fixed because I don't know what you want me to do.  As explained above the original code was written specifying that the values 'Null', '#NULL!', '', ' ', 'Missing', 'Unknown/other', '?', 'NA', '99' would always be None.  So `word,,` is ignored and will be set to None.  Similarly, anything with the values in the list will be ignored and set to None.  The load will be exactly the same whether that line is in the `_values` files or not

**Comment by alvinwmtan** [comment]
@HenryMehta is it possible to privilege the definitions in `_values`? so if `_values` contains `word,,`, we take that to mean "doesn't produce (or understand)" instead of the default None. I'm not sure if this fixes all the issues since I suspect some datasets have an implicit `words,,`...

**Comment by alvinwmtan** [comment]
@HenryMehta when I pull the data in R it still seems to show NA instead of "" for both Danish and Norwegian

**Comment by HenryMehta** [comment]
@alvinwmtan 
I have tried rerunning these several times.  I think everything except Norwegian WG is now ok but please check them all

**Comment by HenryMehta** [comment]
@alvinwmtan also sorted Norwegian WG now

**Comment by alvinwmtan** [comment]
@HenryMehta Danish WS/WG and Norwegian WG all work, but Norwegian WS still seems to have only NAs

**Comment by HenryMehta** [comment]
@alvinwmtan in which fields.  Is it just words that should be blank or if will have nothing is other categories, do they need setting to blank as well?

**Comment by alvinwmtan** [comment]
@HenryMehta It's just words (other categories have an explicit entry for "no", "never" or "not yet"), but Norwegian WS words still only have values "produces" and NA

**Comment by HenryMehta** [comment]
@alvinwmtan I think I've finally got it sorted

**Comment by alvinwmtan** [comment]
Sorry to reopen this, but this problem is also true for Swedish WG (but _not_ WS).

**Comment by HenryMehta** [comment]
@alvinwmtan Deployed to dev

**Comment by alvinwmtan** [comment]
@HenryMehta Issue appears to still be unfixed; Swedish WG still has NA values instead of blank when it is neither "produces" nor "understands".

**Comment by HenryMehta** [comment]
@alvinwmtan I see blanks when I look in Django admin

![image](https://github.com/langcog/wordbank/assets/10542767/c79f1ce3-bcc0-4029-b63c-4e6b45a75031)

**Comment by alvinwmtan** [comment]
@HenryMehta Hmm, I still see only NAs when I directly collect the instrument table:

<img width="896" alt="Screenshot 2023-12-18 at 10 51 10" src="https://github.com/langcog/wordbank/assets/66404649/e5349235-bc35-4c1d-87e2-b239f38ff429">

**Comment by HenryMehta** [comment]
@alvinwmtan In dev these basetable_prt_ids do not refer to Swedish WG.  Or at least they do not show in the admin table for it.  What is your SQL?

**Comment by alvinwmtan** [comment]
@HenryMehta I'm just pulling the whole instrument table labelled `instruments_swedish_wg`: 

<img width="932" alt="Screenshot 2023-12-19 at 08 31 11" src="https://github.com/langcog/wordbank/assets/66404649/f39064eb-4e0a-4487-bc7b-3ad63992ef99">

**Comment by HenryMehta** [comment]
@alvinwmtan I don't think it is holding NA within the field.  I think your system is showing NA when the field is blank.  I could insert a space instead if you want, but the values files for this are the same as other datasets

**Comment by alvinwmtan** [comment]
@HenryMehta I think when it's an empty string it does display it as "" rather than NA (e.g., for Danish below). I'm not sure why this is behaving differently than the other languages…
<img width="936" alt="Screenshot 2023-12-19 at 22 58 52" src="https://github.com/langcog/wordbank/assets/66404649/c8436be7-b698-4b2b-bf81-fb4a09750690">

**Comment by HenryMehta** [comment]
@alvinwmtan Are you using the same system/site and query.  With the Swedish the quotes are not shown whereas they are with the Danish.  This is what I get

<img width="1728" alt="Screenshot 2023-12-20 at 07 20 14" src="https://github.com/langcog/wordbank/assets/10542767/dd5cc871-ed9f-426b-b584-3dda9f4f3a74">

<img width="1728" alt="Screenshot 2023-12-20 at 07 24 27" src="https://github.com/langcog/wordbank/assets/10542767/98b9e149-0250-4637-97be-f023509f1103">

**Comment by HenryMehta** [comment]
@alvinwmtan I think I found the issue.  It seems to be to do with the order the mapping is specified within the _values file.  If you end on a blank (eg word,,) it uses null but if you have another definition after it, then is saves as a blank.  I don't know why, but this seems to have sorted it

**Comment by alvinwmtan** [comment]
@HenryMehta that's good to know—I'll bear that in mind for future imports. Looks good to me now!
