### ISSUE TITLE
static content updates

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#205]
some static content updates:

* [x] homepage: new line of text below "via the wordbankr package": "Explore what we can learn about child language acquisition through Wordbank in the [Wordbank Book](http://wordbank-book.stanford.edu) (MIT Press, 2021)."
* [x] issue #202 
* [x] new box on analysis page at the top, "Wordbank Book" with the following text: "Many common analyses of Wordbank data are described in detail in the Wordbank Book, available at https://wordbank-book.stanford.edu and from MIT Press." Remove box for static reports, right @mikabr ?
* [x] @JMankewitz could you work on finding publications that use wordbank and uploading them so we can update the wordbank pubs page
* [x] on the About page, Yurovsky should have "Carnegie Mellon University" as his affiliation, and there should be a header "Alumni" with Kellier's box listed there. Text for funding should read "The team would like to thank our supporters! The construction of Wordbank was funded by a grant ..." and then the rest the same.

**Comment by mikabr** [comment]
> Remove box for static reports
agreed!

**Comment by HenryMehta** [comment]
@mcfrank I believe I've done the items assigned to me
@JMankewitz if you pass me the publications, I'll add them

**Comment by mcfrank** [comment]
@JMankewitz I think we're waiting on you for pubs, not super urgent but would be good to get this set. here's one that got sent in:

Day, T. K. M., & Elison, J. T. (2021). A broadened estimate of syntactic and lexical ability from the MB-CDI. Journal of Child Language, 1–18. https://doi.org/10.1017/S0305000921000283
