### ISSUE TITLE
[Portuguese_European_WG] - unusual item categories

### ISSUE THREAD

**Issue by kachergis** [langcog/wordbank#209]
e.g., não and sim ("no" and "yes") categorized as "locations" (instead of, e.g., games_routines)

item_310 | nao | word | locations
item_311 | sim | word | locations

**Comment by mcfrank** [comment]
ah - this is wrong in https://github.com/langcog/wordbank/blob/master/raw_data/Portuguese_European_WG/%5BPortuguese_European_WG%5D.csv#L311

They were in the spatial prepositions for WG instrument definitions. This should be fixed and reimported...

**Comment by HenryMehta** [comment]
@kachergis updated

**Comment by alvinwmtan** [comment]
subsumed under #266
