### ISSUE TITLE
Dutch data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#215]
We have some incoming dutch data. We can help with reformatting @HenryMehta if you tell us what you need. 

@Cielke-Hendriks wrote: "In the attachment I added our data. The first document is a combination of a lot of studies, each study using a different CDI (WG, WS, 1, 2A or 2B). Therefore a lot of the cells have the value NA. This means the participant did not have this item on their CDI. Regarding the other values: 0 stands for does not understand or say, 1 for understands and 2 for understand and says. The second document is a single study. This study used a part of a CDI and also added words themselves. This document already has English translations for the CDI items."

[CDI_swingley_matrix.xlsx](https://github.com/langcog/wordbank/files/6498306/CDI_swingley_matrix.xlsx)
[CDI_all_data_finished.csv](https://github.com/langcog/wordbank/files/6498307/CDI_all_data_finished.csv)

**Comment by HenryMehta** [comment]
Hi, @Cielke-Hendriks 
I hope you're well.
I'm looking at your CDI_all_data_finished.csv file and I have a few questions.

1.  Is the subject a unique value to the child or is it the combination of study and subject.  For example subject 2 is against studies story4 and teach3 (and maybe others).  Is this 1 child or 2 children?
2.  The data for sex are v, m, and f.  I don't want to make assumptions so could you confirm what are those are in English
3.   We need to relate the words to word groups (eg verbs, nouns etc) like on WebCDI.  Since you've given the English I can compare to English CDIs and do that.  But I also need to know what the possible responses are and mean for each column.  For example bah can be blank, 1 or 2.  For each column I need to know the potential outputs.

If you could answer these questions I should be able to convert the data into files we can load into Wordbank.

Thanks
Henry

**Comment by Cielke-Hendriks** [comment]
Hi @HenryMehta,

Thanks for the questions. 

1. It is a combination of study and subject. So subject 2 in story4 and teach3 represent 2 different children.
2. v and f both represent female, m represent male
3. The potential outputs for all the words are NA, empty, 1 and 2. Both NA and empty mean the child does not understand or say the word. 1 means the child only understands the word. 2 means the child understands and says the word.

I hope this aswers your questions.

Best,
Cielke

**Comment by mcfrank** [comment]
Citation is: Bergmann, Christina, Hendriks, Cielke, de Bruin, Yvette, Egger, Julia, Fikkert, Paula, Hahn, Laura, Hunnius, Sabine, Johnson, Elisabeth, Junge, Caroline, Levelt, Claartje, Rulkens-Dijkstra, Nienke, Swingley, Daniel, Ward, Emma, & Rowland, Caroline. MB-CDI Dutch Pre-Norming Corpus. https://osf.io/z3msf/

License is CC-BY

**Comment by alv1nn** [comment]
Hi @Cielke-Hendriks, just wanted to check something: in CDI_swingley_matrix.xlsx, the column labelled "nothing / niets" has notes in some of the cells (instead of 1, 2, or blank)—is this intentional? Thanks!

**Comment by Cielke-Hendriks** [comment]
Hi @alv1nn, it seems like something went wrong in that column. I don't think it is intentional and I think it is best to omit the data in the "nothing / niets" column.

**Comment by HenryMehta** [comment]
@alvinwmtan I'm getting ready to look at this dataset next - have you already done the work to create the _data, )value and _field files?  I just don't want to duplicate effort

**Comment by HenryMehta** [comment]
@alvinwmtan 
I have started loadingd the Swingley data.  Study2, Study3 and Study 4 are loaded.

Teach3 and Xeno both have several administrations without an age.  What would you like me to use there?

With the Xeno study, all the data within the niets column were different.  I simply deleted the data for the load.  Let me know if I should be doing something else.

**Comment by HenryMehta** [comment]
@alvinwmtan Both are now loaded to dev

**Comment by HenryMehta** [comment]
@alvinwmtan For the CDI_all_data_finished there are a number of different forms in the column, but we have responses for all so do I simply do a single combined form of all the data?

**Comment by alvinwmtan** [comment]
@HenryMehta We should have different forms (WS, WG, 1, 2A, 2B, 3). Each form should be the set of all items that have a non-NA response in _any_ administration marked with that form. 

I've put together a CSV with all the items here: 
[dutch_unilemmas.csv](https://github.com/langcog/wordbank/files/8373608/dutch_unilemmas.csv)

Alternatively, if the form specs are more helpful, these are available here:
[[Dutch_Form1].csv](https://github.com/langcog/wordbank/files/8373675/Dutch_Form1.csv)
[[Dutch_Form2A].csv](https://github.com/langcog/wordbank/files/8373677/Dutch_Form2A.csv)
[[Dutch_Form2B].csv](https://github.com/langcog/wordbank/files/8373678/Dutch_Form2B.csv)
[[Dutch_Form3].csv](https://github.com/langcog/wordbank/files/8373679/Dutch_Form3.csv)
[[Dutch_WG].csv](https://github.com/langcog/wordbank/files/8373680/Dutch_WG.csv)
[[Dutch_WS].csv](https://github.com/langcog/wordbank/files/8373681/Dutch_WS.csv)

(Note that these are likely to be updated soon as we're doing a round of checking/updating across all form specs.)

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
Hi Cielke, I wonder if you can help.  I am looking at the CDI_all_data_finished.csv file.  We don't have IDs for the administrations so I don't know if each administration is for a different child.  But we do have a Longitudinal_id.  Does the Longitudinal_id correspond to one child and those without the Longitudinal_id are single administrations for a single child.
Thanks in advance
Henry

**Comment by HenryMehta** [comment]
@alvinwmtan I'm working on the Dutch_WS as per the file you gave above.  I'm having trouble with this because your data doesn't match with the datasets given.  For example, you've got vroem and broem as separate words but the dataset has them as one vroem/broem(auto).

I don't know how I should be handling this

**Comment by Cielke-Hendriks** [comment]
@HenryMehta 
Hi Henry. Yes, you are correct. When there is no longitudinal_id, it is just a single administration for a single child. When there is a longitudinal_id, it means that child can have multiple administrations in this file. It is, however, not always the case that a child with a longitudinal_id has multiple administrations in this file (if they for example dropped out of the study and we only have the CDI on the first age, but they still got the longitudinal_id anyway).

**Comment by alvinwmtan** [comment]
@HenryMehta I think it's the Swingley CDI that has `vroem` and `broem` separate; the `[Dutch_WS].csv` file should have `vroem/broem(auto)` as a single item? Unless I've mistaken what you meant?

**Comment by HenryMehta** [comment]
@alvinwmtan I used the [Dutch_WS].csv above.  This has them as single items

**Comment by HenryMehta** [comment]
Sorry, I must have done something really stupid, like copying the Swingley file across and renaming it or something - really sorry

**Comment by alvinwmtan** [comment]
No worries, all good (:

**Comment by HenryMehta** [comment]
@alvinwmtan Dutch_WG has column `tandjespoetsen` with values `no` and `yes`.

**Comment by HenryMehta** [comment]
@alvinwmtan I have now deployed all the Dutch data

**Comment by alvinwmtan** [comment]
@HenryMehta Some issues:
- For the Swingley datasets, three items weren't correctly imported: `item_271`, `item_299`, and `item_381`. I have no idea why this might be the case, but wordbank2 has 0s for all of them, whereas the raw files have non-zero values.
- Dutch WG has issues with `item_250`, `item_279`, and `item_400`: wordbank2 again has 0, whereas the raw files have non-zero values
- Dutch WG BRC: "yes" and "no" should be "understands" and "" respectively; sorry for not noticing this earlier
Everything else looks correct

**Comment by HenryMehta** [comment]
> * For the Swingley datasets, three items weren't correctly imported: `item_271`, `item_299`, and `item_381`. I have no idea why this might be the case, but wordbank2 has 0s for all of them, whereas the raw files have non-zero values.

When I run SQL against the database directly, `item_271`, `item_299` and `item_381` all have non-zero values
I've also got data in the WG fields.  I have rerun the WG files with `yes` replaced by `understands` and `no` replaced by `''`

**Comment by HenryMehta** [comment]
> * For the Swingley datasets, three items weren't correctly imported: `item_271`, `item_299`, and `item_381`. I have no idea why this might be the case, but wordbank2 has 0s for all of them, whereas the raw files have non-zero values.

When I run SQL against the database directly, `item_271`, `item_299` and `item_381` all have non-zero values
I've also got data in the WG fields.  I have rerun the WG files with `yes` replaced by `understands` and `no` replaced by `''`

**Comment by alvinwmtan** [comment]
@HenryMehta Okay a bit more rummaging around the database reveals:

- Dutch Swingley
  - `item_271` contains `understa` and `produces`
  - `item_299` contains `unders` and `produc`
  - `item_381` contains `underst` and `produce`
  - all other items contain `understands` and `produces`. 

- Dutch WG
  - `item_250` and `item_279` have `yes` and `no`
  - `item_400` has `unde` instead of `understands`
  - all other items have `understands` and `produces`. 

Our R code was not pulling all of these variants, but requires *one standard variant*. The values of `understands` and `produces` are correct and should be default everywhere. (Additionally, during testing @mikabr and I also found other datasets which contain `understa`; this should be corrected to `understands` across the board, but that's a separate issue.)

**Comment by HenryMehta** [comment]
@alvinwmtan Something strange - the shortened entries made me take a look at the model files produce from the 02_create_instrument script and it produced fields too small to hold the whole word.  I've corrected for Swinley and I'm reloading now.

But the WG file is very strange.  It should have rows like: `item_399_choices = [('understands', 'understands'), ('produces', 'produces')]`
But has rows like: `item_401_choices = [('understands;produces', 'understands;produces')]`

Can you give me all the language form combinations you've come across with shortened entries and I'll trawl through the model files - probably best to do via a new issue

**Comment by HenryMehta** [comment]
Although I think the issue causing the model files to be generated incorrectly for the items above is the [].csv file provides the choices as `understands;produces` but a space is needed so it should be `understands; produces`

**Comment by HenryMehta** [comment]
And the shortened fields appear to be when an entry has a comma between quotes so things are being thrown off.  For example
`item_299,"fair, fancy fair",kermis,kermis,understands; produces,"fair, fancy fair",word,` is being split into the fields:

- item_299
- "fair
- fancy fair"
- kermis
- kermis
- understands; produces
- "fair
- fancy fair"
- word

Whereas it should be :

- item_299
- "fair, fancy fair"
- kermis
- kermis
- understands; produces
- "fair, fancy fair"
- word

I'll take a look on Monday

**Comment by HenryMehta** [comment]
@alvinwmtan I believe this now sorted

**Comment by alvinwmtan** [comment]
@HenryMehta Yup, this dataset looks good pulled from R!
