### ISSUE TITLE
Poulin-Dubois bilingual data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#216]
"I attach an Excel file with the data for the first 2 waves of our longitudinal study (at 16 and 22  months, as reported in Legacy et al 2016 and 2018 ). Individual items for Wave 3 (around 29 mos) need to be entered.  This will be done shortly,

I checked with my collaborators and we give you permission to make these data available to Wordbank. We also have data from Spanish-English bilinguals from this project and we will see when these can be made available. "
[Request_MCDIData(Wave1_2_3)_updated.xls](https://github.com/langcog/wordbank/files/6498404/Request_MCDIData.Wave1_2_3._updated.xls)

**Comment by ningkko** [comment]
Here are the pre-cleaned French-English data from Prof. Poulin-Dubois, numbers indicate wave numbers (2 = wave 2).
[French_English_2.csv](https://github.com/langcog/wordbank/files/6951134/French_English_2.csv)
[French_English_3.csv](https://github.com/langcog/wordbank/files/6951135/French_English_3.csv)
[french_english_data_2.csv](https://github.com/langcog/wordbank/files/6951136/french_english_data_2.csv)
[french_english_data_3.csv](https://github.com/langcog/wordbank/files/6951137/french_english_data_3.csv)

**Comment by ningkko** [comment]
And here's the translation of CDI words in French to English
[Words and Gestures TE List (formatted).xlsx](https://github.com/langcog/wordbank/files/6951171/Words.and.Gestures.TE.List.formatted.xlsx)

**Comment by alv1nn** [comment]
Hi @ningkko , do you know if there's cleaned data for wave 1?

**Comment by alvinwmtan** [comment]
Hi Henry, here are the cleaned data files:
[EnglishWG_PoulinDubois_data.csv](https://github.com/langcog/wordbank/files/8311679/EnglishWG_PoulinDubois_data.csv)
[EnglishWG_PoulinDubois_fields.csv](https://github.com/langcog/wordbank/files/8311680/EnglishWG_PoulinDubois_fields.csv)
[EnglishWG_PoulinDubois_values.csv](https://github.com/langcog/wordbank/files/8311681/EnglishWG_PoulinDubois_values.csv)
[EnglishWS_PoulinDubois_data.csv](https://github.com/langcog/wordbank/files/8311682/EnglishWS_PoulinDubois_data.csv)
[EnglishWS_PoulinDubois_fields.csv](https://github.com/langcog/wordbank/files/8311683/EnglishWS_PoulinDubois_fields.csv)
[EnglishWS_PoulinDubois_values.csv](https://github.com/langcog/wordbank/files/8311684/EnglishWS_PoulinDubois_values.csv)
[FrenchQuebecoisWG_PoulinDubois_data.csv](https://github.com/langcog/wordbank/files/8311685/FrenchQuebecoisWG_PoulinDubois_data.csv)
[FrenchQuebecoisWG_PoulinDubois_fields.csv](https://github.com/langcog/wordbank/files/8311686/FrenchQuebecoisWG_PoulinDubois_fields.csv)
[FrenchQuebecoisWG_PoulinDubois_values.csv](https://github.com/langcog/wordbank/files/8311687/FrenchQuebecoisWG_PoulinDubois_values.csv)
[FrenchQuebecoisWS_PoulinDubois_data.csv](https://github.com/langcog/wordbank/files/8311688/FrenchQuebecoisWS_PoulinDubois_data.csv)
[FrenchQuebecoisWS_PoulinDubois_fields.csv](https://github.com/langcog/wordbank/files/8311689/FrenchQuebecoisWS_PoulinDubois_fields.csv)
[FrenchQuebecoisWS_PoulinDubois_values.csv](https://github.com/langcog/wordbank/files/8311690/FrenchQuebecoisWS_PoulinDubois_values.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan @ningkko @mcfrank

**Comment by alvinwmtan** [comment]
@HenryMehta That's correct; these are longitudinal data of the same set of children (with some dropouts) across three time points (one WG and two WS) x two languages (English and Quebecois French)

**Comment by HenryMehta** [comment]
@alvinwmtan 
Thanks
Also, Could I have citation and contributor?

**Comment by alvinwmtan** [comment]
@HenryMehta I believe it's the following (unless @mcfrank or @ningkko know if another citation would be preferred?):

Legacy, J., Zesiger, P., Friend, M., & Poulin-Dubois, D. (2018). Vocabulary size and speed of word recognition in very young French–English bilinguals: A longitudinal study. Bilingualism: Language and Cognition, 21(1), 137–149.

Contributor: Diane Poulin-Dubois, Concordia University

**Comment by HenryMehta** [comment]
@alvinwmtan @mcfrank @ningkko 
I have a problem with Subject 440 for both the French WS and WG datasets.  This subject has no age.  Currently the database requires that this field is not null.
I think the options we have available are:
1 add the data (if available)
2 enable null
3 ignore row

**Comment by alvinwmtan** [comment]
@HenryMehta I think we'll propagate the data from the English WS/WG, so 16.7 for WG and 23.6 for WS

**Comment by HenryMehta** [comment]
@alvinwmtan data now loaded and available to check

**Comment by alvinwmtan** [comment]
Hi @HenryMehta, apologies as I've made a mistake in the values files. The WS files should have `1` as `produces` for `type == word`, and no `2` values. Sorry about this.

**Comment by HenryMehta** [comment]
@alvinwmtan 
The French WS data file has one cell with a 2 in it (in the salle de bain column).  I've set both 1 and 2 to produces.  Let me know if this is wrong

Now deployed

**Comment by alvinwmtan** [comment]
@HenryMehta I think 2 to NA is probably more "correct"

**Comment by HenryMehta** [comment]
@alvinwmtan ok - amended and deployed

**Comment by alvinwmtan** [comment]
@HenryMehta Great, I've just checked in R and this dataset is good to go!
