### ISSUE TITLE
identifying information in raw data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#221]
hi @vmarchman, I just got an email noting that "as a heads up, it appears birthdate is present in the EnglishWS_Marchman_Norming_data.csv file, under the V4 header." 

we should get rid of this. 

@HenryMehta - at some point would it be possible to remove this information from the CSV? 

thanks!

**Comment by HenryMehta** [comment]
@mcfrank 
I can delete the column from the data but that will not remove it from GitHub history.  If you want that cleared I need to remove that file from all history and the reload it to the latest deployment.  Is that what you actually want?

**Comment by mcfrank** [comment]
Hi Henry, good point about the history. I think we do need to remove it
from the history and then re-add the anonymized file to the most recent
version.

**Comment by HenryMehta** [comment]
Could someone confirm the column heading which has DOB in it.  The 3 possible headings are V4, V6, and DateOfCDI (and I don't think it is DateofCDI).

**Comment by vmarchman** [comment]
Hi @HenryMehta - It's V4.

**Comment by HenryMehta** [comment]
Master updated
