### ISSUE TITLE
fix hebrew reference

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#223]
should be: 

Gendler-Shalev, H., & Dromi, E. (2021). The Hebrew Web Communicative Development Inventory (MB-CDI): Lexical Development Growth Curves. Journal of Child Language, 1–17. https://doi.org/10.1017/S0305000921000179

**Comment by alvinwmtan** [comment]
@HenryMehta the citation for the Hebrew WG dataset should be this

**Comment by HenryMehta** [comment]
@alvinwmtan I've replaced the Hebrew WG citation for the Shalev dataset. I don't have a WS citation for the Shalev dataset. Deployed to dev to ensure it is right

**Comment by alvinwmtan** [comment]
@HenryMehta sorry, I seem to still see the old citation? (possibly overwritten by the change from #282)?

**Comment by HenryMehta** [comment]
@alvinwmtan Just trying to deploy this again now

**Comment by HenryMehta** [comment]
@alvinwmtan I've realised what the problem is - I'll have to revisit Friday

**Comment by alvinwmtan** [comment]
@HenryMehta looks good now

**Comment by HenryMehta** [comment]
@alvinwmtan I think this might already be in production as well
