### ISSUE TITLE
English-Hebrew data

### ISSUE THREAD

**Issue by ningkko** [langcog/wordbank#224]
@mcfrank @HenryMehta Hi, here are the precleaned English-Hebrew data from "A CDI Study of Bilingual English-Hebrew Children--Frequency of Exposure as a Major Source of Variation". 

[English_Hebrew_data_2.xls](https://github.com/langcog/wordbank/files/6843818/English_Hebrew_data_2.xls)
[English_Hebrew_data.csv](https://github.com/langcog/wordbank/files/6843819/English_Hebrew_data.csv)
[English_Hebrew.csv](https://github.com/langcog/wordbank/files/6843820/English_Hebrew.csv)

**Comment by HenryMehta** [comment]
@mcfrank Can you advice the characterset being used?  I need to convert it to UTF8 to load to Python and this isn't in UTF8 so I need to know what to open as initially

**Comment by ningkko** [comment]
I was able to load it using pandas. Does ASCII or ISO-8859-8 work?

**Comment by HenryMehta** [comment]
@ningkko I'm not sure why this didn't work for me yesterday but did today.  Anyway, I've got all 3 open but could you confirm English_Hebrew.csv for me.    It seems to have the same word over definition/gloss over several lines with different itemIDs. 

I really need something with itemID, item, type, category, choices, definition, gloss, uni_lemma, complexity_category.

ItemID is there, 
item would be the Hebrew word, 
type will usually be 'word', 
category is there, 
choices I can work out, 
definition is there, 
gloss is there.

I don't think complexity_category is needed but I think uni_lemma is.

**Comment by alvinwmtan** [comment]
Hi Henry, apologies for not sending this over earlier, but I've cleaned and tidied all the files into the correct data/fields/values format as per the specs:

[EnglishWS_Armon-Lotem_data.csv](https://github.com/langcog/wordbank/files/8311673/EnglishWS_Armon-Lotem_data.csv)
[EnglishWS_Armon-Lotem_fields.csv](https://github.com/langcog/wordbank/files/8311674/EnglishWS_Armon-Lotem_fields.csv)
[EnglishWS_Armon-Lotem_values.csv](https://github.com/langcog/wordbank/files/8311675/EnglishWS_Armon-Lotem_values.csv)
[HebrewWS_Armon-Lotem_data.csv](https://github.com/langcog/wordbank/files/8311676/HebrewWS_Armon-Lotem_data.csv)
[HebrewWS_Armon-Lotem_fields.csv](https://github.com/langcog/wordbank/files/8311677/HebrewWS_Armon-Lotem_fields.csv)
[HebrewWS_Armon-Lotem_values.csv](https://github.com/langcog/wordbank/files/8311678/HebrewWS_Armon-Lotem_values.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan 

I hope I've understood this correctly.  I've created a new Hebrew instrument called WS_b (numbers get stripped out).  
I've loaded the data above.

I need contributor and citation to add to the dataset if available

**Comment by alvinwmtan** [comment]
@HenryMehta I was thinking of merging the two Hebrew WS instruments actually, such that the existing dataset just has NAs for all the new items that were added (and the new dataset has NAs for some of the old items which were omitted). Does that make sense?

Contributor: Sharon Armon-Lotem
Citation: Armon-Lotem, S. & Ohana, O. (2017). A CDI study of bilingual English-Hebrew children: Frequency of exposure as a major source of variation. International Journal of Bilingual Education and Bilingualism, 20(2), 201–217.

**Comment by mcfrank** [comment]
I think that’s a good move!
-- 
Mike

**Comment by HenryMehta** [comment]
ok - that's done.  Moved to Hebrew WS and citations added

**Comment by alvinwmtan** [comment]
@HenryMehta Data checked from R; this dataset is good to go!
