### ISSUE TITLE
Bilingual question: How do code exposure?

### ISSUE THREAD

**Issue by jkhartshorne** [langcog/wordbank#225]
Some of our datasets include information on relative exposure (more English? more the other language?) or age of first exposure if there is an early L2 (e.g., 1;8). Is this information you plan on capturing in WordBank? If so, how?

**Comment by HenryMehta** [comment]
@jkhartshorne I have recently made some code changes which will facilitate capturing this data.  It is being tested at the moment.  A description of how the data is captured is shown [here](https://github.com/langcog/wordbank/wiki/DEVELOPMENT---Instructions-will-multilingual-added)

**Comment by jkhartshorne** [comment]
Ahh, I didn't read the detail on your 'language' field, which I think is how you are intending to capture this?

I'm not sure how often you'll have that specific number (proportion of each language). In the datasets we have so far, it's usually something else, such as proportion of time spent in each language with each of several caregivers. Or if it's proportion for the child, it's on a Likert scale. 

Is the idea that we'd only report proportion language when it's actually provided in the format suggested in your doc? Or is there going to be a conversion policy? Or should each coder invent their own conversion system and just document it?

**Comment by HenryMehta** [comment]
@jkhartshorne Sorry, I really don't know, this is how I was asked to develop the system.

@mcfrank is probably best placed to respond
