### ISSUE TITLE
Erika Hoff - Spanish_English_Bilingual Data

### ISSUE THREAD

**Issue by ningkko** [langcog/wordbank#226]
[Spanish_English_HDPM_data2.csv](https://github.com/langcog/wordbank/files/6951550/Spanish_English_HDPM_data2.csv)
[Spanish_English.csv](https://github.com/langcog/wordbank/files/6951551/Spanish_English.csv)
[Spanish-English_data(HDPM, Bilingual).csv](https://github.com/langcog/wordbank/files/6951552/Spanish-English_data.HDPM.Bilingual.csv)

**Comment by ningkko** [comment]
[Spanish_English_R01_data2.csv](https://github.com/langcog/wordbank/files/6951554/Spanish_English_R01_data2.csv)
[Spanish_English_R01.csv](https://github.com/langcog/wordbank/files/6951555/Spanish_English_R01.csv)
[Spanish-English(R01, Bilingual).csv](https://github.com/langcog/wordbank/files/6951556/Spanish-English.R01.Bilingual.csv)

**Comment by HenryMehta** [comment]
@ningkko @mcfrank 
Can you:

- Confirm gender = 1 is Male, 0 is Female, blank is other
- Confirm Mother and Father eduction_03 are scored as follows: {(1, 'None'), (2, 'Primary'), (3, 'Some Secondary'), (4, 'Secondary'), (5, 'Some College'), (6, 'College'), (7, 'Some Graduate'), (8, 'Graduate')}
- Provide breakdowns and explanations of the other columns in the xxxs_data2 files.

I believe the input_percent_Eng_home_30 is the percentage of English spoken at home (so 100 is 100% English 0% Spanish)?  Is that correct?  And is there an age of acquisition for the language?

Are the two dataset (R01 & HPDM) related in any way?

**Comment by ningkko** [comment]
Confirming with Erika

**Comment by alvinwmtan** [comment]
Hi Henry, if it helps I've tidied these into the spec format, but don't have the answers to your questions either (hence the `fields` csvs have a lot of missing entries. 

The `input_percent_Eng_home_30` is indeed percentage of English spoken, measured at age 30m. I don't think there is age of first exposure information. The other columns are all metrics measured at age 30m, but I believe the only field we're actually interested in is `Mother_education_30` which is mom_ed

[EnglishWS_Hoff_HDPM_data.csv](https://github.com/langcog/wordbank/files/8311717/EnglishWS_Hoff_HDPM_data.csv)
[EnglishWS_Hoff_HDPM_fields.csv](https://github.com/langcog/wordbank/files/8311718/EnglishWS_Hoff_HDPM_fields.csv)
[EnglishWS_Hoff_HDPM_values.csv](https://github.com/langcog/wordbank/files/8311719/EnglishWS_Hoff_HDPM_values.csv)
[EnglishWS_Hoff_R01_data.csv](https://github.com/langcog/wordbank/files/8311720/EnglishWS_Hoff_R01_data.csv)
[EnglishWS_Hoff_R01_fields.csv](https://github.com/langcog/wordbank/files/8311721/EnglishWS_Hoff_R01_fields.csv)
[EnglishWS_Hoff_R01_values.csv](https://github.com/langcog/wordbank/files/8311722/EnglishWS_Hoff_R01_values.csv)
[SpanishMexicanWS_Hoff_HDPM_data.csv](https://github.com/langcog/wordbank/files/8311723/SpanishMexicanWS_Hoff_HDPM_data.csv)
[SpanishMexicanWS_Hoff_HDPM_fields.csv](https://github.com/langcog/wordbank/files/8311724/SpanishMexicanWS_Hoff_HDPM_fields.csv)
[SpanishMexicanWS_Hoff_HDPM_values.csv](https://github.com/langcog/wordbank/files/8311725/SpanishMexicanWS_Hoff_HDPM_values.csv)
[SpanishMexicanWS_Hoff_R01_data.csv](https://github.com/langcog/wordbank/files/8311726/SpanishMexicanWS_Hoff_R01_data.csv)
[SpanishMexicanWS_Hoff_R01_fields.csv](https://github.com/langcog/wordbank/files/8311727/SpanishMexicanWS_Hoff_R01_fields.csv)
[SpanishMexicanWS_Hoff_R01_values.csv](https://github.com/langcog/wordbank/files/8311728/SpanishMexicanWS_Hoff_R01_values.csv)

**Comment by mcfrank** [comment]
See email from Ning. :)

**Comment by HenryMehta** [comment]
Response from Erika


> Okay, I can answer your questions now
> 
> Gender: 0=female, 1=male
> Language status: 0=monolingual, 1=bilingual
> Father education lang 30 (this is the language in which the father attained his highest level of education, recorded at child age 30 mon ths: 1=English, 2=Spanish, 3=other
> Mother education ...the same for the mother
> Chronological age 30: this is the exact age of the child at time of assessment (30 means the child was 30 months old plus or minus a few weeks)
> Input percent English home 30: the percent of the child's language exposure at home that was in English at the 30-month assessment point. Spanish exposure is almost 100% - English exposure percent; there were a very few children that heard a third language at home, and none heard a third language for more than 5% of their exposure)
> 
> Mother and father education are coded as follows: 0=no education, 1=less than high school, 2=high school, 3=2 yr degree, 4=4yr degree, 5=advanced degree. (I'm not aware of any place that education was coded 1 - 8, but if you find such a thing let me know and I will pursue it.)
> 
> R01 v HDPM
> 
> Subjects with these different prefixes were recruited under different grant mechanisms (and someone in the lab thought this was a good way to assign ID numbers). I don't think this difference should matter for your purposes. All R01 participants have at least one immigrant parent, born in a Spanish-speaking country, and Spanish is used in the home --for some only Spanish is used initially at least. There are a just a few HDPM participants who have no immigrant parent, but they all hear Spanish and English at home.
> 
> I hope this answers your questions. Just let me know if I overlooked something.
> 
> Best,
> 
> Erika
>

**Comment by alvinwmtan** [comment]
I suppose this means that we combine the R01 and HDPM datasets, instead of having them separate.

@ningkko do you have a reference (article) for the dataset so that we can attach a citation when we put it up?

**Comment by HenryMehta** [comment]
What citation and contributor should I enter?

**Comment by HenryMehta** [comment]
Also, I don't know how to decode the ethnicity column and mom_ed has a value of -997 on some English R01 rows.  For the time-being I've set this to be no education

**Comment by HenryMehta** [comment]
@ningkko @alvinwmtan @mcfrank 
I have now loaded these datasets - I know I'll need to load again once Ethnicity decode is available, but I now know the data all loads.
Please take some time to check however you do with R that it looks right from your POV and let me know

**Comment by alvinwmtan** [comment]
@HenryMehta -997 for mom_ed should be null if that's possible. Contributor is Erika Hoff, Florida Atlantic University

@ningkko could you double-check with Erika on the citation and on the ethnicity coding?

**Comment by ningkko** [comment]
I have a citation list. Will send later and ask about the ethnicity coding

**Comment by HenryMehta** [comment]
> @HenryMehta -997 for mom_ed should be null if that's possible. Contributor is Erika Hoff, Florida Atlantic University
> 
> @ningkko could you double-check with Erika on the citation and on the ethnicity coding?

null isn't allowed currently.  I can amend the code to allow it if required

**Comment by HenryMehta** [comment]
@alvinwmtan Null has now been enabled and these files are loaded and available to check

**Comment by alvinwmtan** [comment]
Hi @HenryMehta, apologies as I made a typo error in the Spanish fields file (had duplicate `item_103` instead of one `item_102` and one `item_103`)
[SpanishMexicanWS_Hoff_fields.csv](https://github.com/langcog/wordbank/files/8413022/SpanishMexicanWS_Hoff_fields.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan fix deployed

**Comment by alvinwmtan** [comment]
@HenryMehta Pulling from R seems to not reflect the change—and now the English WS seems to only pull from the HDPM dataset, and not the R01 one? Not sure what might be the cause.

**Comment by HenryMehta** [comment]
@alvinwmtan I found an error in the R01 dataset which I didn't notice yesterday.  I've amended and deployed

**Comment by HenryMehta** [comment]
@alvinwmtan I cannot find anything wrong with HDPM so I am reloading it.  I wonder if I thought I had done it but hadn't.

**Comment by alvinwmtan** [comment]
@HenryMehta Sorry Henry, it seems like both English and Spanish (Mexican) now only have the HDPM dataset. Would it be easier if I combined the `data` files so there's only one file for each language?

**Comment by HenryMehta** [comment]
@alvinwmtan @mikabr 

ok - I've worked out the issue.  At the moment we do not use the `dataset['dataset']` field in the `dataset.json` file if we have a `dataset_origin` field.

I would like to add this field to the `dataset` table which I'll then be able to use to distinguish different datasets with the same instrument and same `dataset_origin`.

Can you confirm this is ok and will not cause an issue in R

**Comment by alvinwmtan** [comment]
@HenryMehta Yup this should be okay

**Comment by mcfrank** [comment]
@alvinwmtan 

The ethnicity code is

1 = African American
2 = Hispanic White
3 = Hispanic African
4 = European American
5 = Asian
6 = Other

The HDPM subject numbers are published in Hoff et al. 2012:

Hoff, E., Core, C., Place, S., Rumiche, R., Señor, M., & Parra, M. (2012). Dual language exposure and early bilingual development. Journal of child language, 39(1), 1-27.

The R01 subject numbers are published in this:

Hoff, E., Quinn, J. M., & Giguere, D. (2018). What explains the correlation between growth in vocabulary and grammar? New evidence from latent change score analyses of simultaneous bilingual development. Developmental science, 21(2), e12536.

**Comment by mcfrank** [comment]
@alvinwmtan 

The ethnicity code is

1 = African American
2 = Hispanic White
3 = Hispanic African
4 = European American
5 = Asian
6 = Other

The HDPM subject numbers are published in Hoff et al. 2012:

Hoff, E., Core, C., Place, S., Rumiche, R., Señor, M., & Parra, M. (2012). Dual language exposure and early bilingual development. Journal of child language, 39(1), 1-27.

The R01 subject numbers are published in this:

Hoff, E., Quinn, J. M., & Giguere, D. (2018). What explains the correlation between growth in vocabulary and grammar? New evidence from latent change score analyses of simultaneous bilingual development. Developmental science, 21(2), e12536.

**Comment by alvinwmtan** [comment]
@HenryMehta it'd be great if you could update (1) the ethnicity values in the `_values.csv` and (2) the citations for these datasets

**Comment by HenryMehta** [comment]
@alvinwmtan 
I've done the citations.

The ethnicity values allowed in the database are 
`ethnicities = (('A', 'Asian'), ('B', 'Black'), ('H', 'Hispanic'), ('W', 'White'), ('O', 'Other/Mixed'))`

I can add the items above that don't fit, or could you let me know how to map them

**Comment by alvinwmtan** [comment]
(see #263) ethnicity/race coding should be:
1 = African American `{ethnicity: N, race: B}`
2 = Hispanic White `{ethnicity: H, race: W}`
3 = Hispanic African `{ethnicity: H, race: B}`
4 = European American `{ethnicity: N, race: W}`
5 = Asian `{ethnicity: N, race: A}`
6 = Other `{ethnicity: N, race: O}`
