### ISSUE TITLE
hungarian data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#227]
From Kas Bence: "I am terribly sorry that it took so long for me to get back to you with this. The end of the last university year was extremely difficult in the pandemic and a life-saving holiday also contributed to the delay. But now I have some good news as I could finish the database I can offer at present to the Wordbank site. Please find attached the data file consisting of item-by-item vocabulary data of 372 children aged 16-30 months gathered cross-sectionally with the Hungarian CDI WS form. 
In each sheet there are two heading rows (English and Hungarian). In the first sheet there are the sums of the vocabulary sections (along with the total words score) and in the other 4 sheets you can find the data for each item in the form. I also attached the Hungarian WS form for orientation. Items in both English and Hungarian versions are marked by a combination of letters referring to the section they belong to e.g. 'an_owl' means the word 'owl' in the section of Animals (an).
I hope the data can be processed in this format. Please tell me if there is anything I should add or re-organize in this database. In the future I will go on working with the grammar part of the data although I am not sure that is relevant to the Wordbank. "

[KOFA-2.pdf](https://github.com/langcog/wordbank/files/7008505/KOFA-2.pdf)
[HCDI2-WS-vocabulary-data.xlsx](https://github.com/langcog/wordbank/files/7008508/HCDI2-WS-vocabulary-data.xlsx)

**Comment by kachergis** [comment]
data and instrument ready for import!
