### ISSUE TITLE
Add Argentinian WS data

### ISSUE THREAD

**Issue by vmarchman** [langcog/wordbank#228]
Will be receiving data from Mariela Resches for Argentine data

**Comment by vmarchman** [comment]
Received the data for Argentine Spanish WS from Mariela! 

[cdi2arg784_wordbank.csv](https://github.com/langcog/wordbank/files/8265914/cdi2arg784_wordbank.csv)

Here's the coding for Sex and maternal education:

Sex:  1 = Male, 2 = Female

Scale for Maternal education:

1= uncomplete primary education 
2= Primary (elementary) school
3= Uncomplete secondary education (middle school -some high school)
4= Secondary education (high school = 12 years of education )
5= uncomplete tertiary education ( some technical study /community college)
6= Tertiary Education (Technical degree)
7= uncomplete university degree
8= University degree or more

**Comment by HenryMehta** [comment]
@vmarchman Can you advice what character set is being used for the words.  It doesn't open correctly with UTF8 which is what I will need to convert it to for Python and to load

**Comment by HenryMehta** [comment]
@vmarchman For the items is 1 understands, 2 produces (there are none)?

**Comment by HenryMehta** [comment]
@vmarchman I'm having trouble creating this file for Argentine because I don't know the translations.  I can try muddling through slowly and then send through for someone to check, but I suspect it will take me several hours - and I suspect I will have the same issue with other datasets

[[Spanish_European_WS].csv](https://github.com/langcog/wordbank/files/8308880/Spanish_European_WS.csv)
v

**Comment by vmarchman** [comment]
@Henry ***@***.***> Yes, I am in the process of getting
translations for these.  They are very similar to the Mexican Spanish, but
hold off for now.  I should be able to have those for you soon.

Thanks.

**Comment by vmarchman** [comment]
@HenryMehta @alvinwmtan Here are the glosses from Mariela. 
[Spanish_Argentinian_WS_april6_22.xlsx](https://github.com/langcog/wordbank/files/8443929/Spanish_Argentinian_WS_april6_22.xlsx)

**Comment by vmarchman** [comment]
Also - this is WS, so 1 = produces 0 = does not produce

**Comment by HenryMehta** [comment]
@vmarchman @alvinwmtan Deploy and ready to check

**Comment by alvinwmtan** [comment]
@HenryMehta Data pulled in R and okay, although there is a typo in the `dataset_name` and `dataset_origin_name`: it should be Re**s**ches not Reches.

**Comment by HenryMehta** [comment]
@alvinwmtan I'm not going to change that now because it will then try and load it twice

**Comment by alvinwmtan** [comment]
@HenryMehta would it be possible to delete the instrument table and reload? I think it's probably quite important to spell the name of the contributor correctly

**Comment by HenryMehta** [comment]
@alvinwmtan I think that is now done.

**Comment by alvinwmtan** [comment]
@HenryMehta looks good now, thanks!

**Comment by alvinwmtan** [comment]
@HenryMehta really sorry about this, but I was taking a look at the raw data for this and noticed that the form had some sentence complexity items at the end that were being coded as words. I've now corrected this and reformatted the files:

[[Spanish_Argentinian_WS].csv](https://github.com/langcog/wordbank/files/8543431/Spanish_Argentinian_WS.csv)
[Spanish_Argentinian_WS_Resches_data.csv](https://github.com/langcog/wordbank/files/8543432/Spanish_Argentinian_WS_Resches_data.csv)
[Spanish_Argentinian_WS_Resches_fields.csv](https://github.com/langcog/wordbank/files/8543434/Spanish_Argentinian_WS_Resches_fields.csv)
[Spanish_Argentinian_WS_Resches_values.csv](https://github.com/langcog/wordbank/files/8543435/Spanish_Argentinian_WS_Resches_values.csv)

**Comment by vmarchman** [comment]
Here's the citation for the Argentine Spanish WS @alvinwmtan 

Resches, M., Querejeta, M., Kohan Cortada, A., & Laguens, A. (2021). Adaptación y normativización del Inventario del Desarrollo Comunicativo MacArthur-Bates (CDI-Forma II) al español rioplatense [Adaptation and standardization of the MacArthur-Bates Communicative Development Inventory (CDI-Form II) to River Plate Spanish]. Revista Iberoamericana de Psicología; 14(3), 107-120. https://doi.org/10.33881/2027-1786.rip.14310
