### ISSUE TITLE
Chilean Spanish

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#233]
"I attach the data from the pilot test. I deleted the personal data. Participants who were eliminated due to exclusion criteria are not included, if you need them, let me know. The file is not modified as a database either, we will do that later but I think it works for the wordbank. The instrument begins in column X, and in other tabs there are some descriptive analyzes.

And of course, in the large sample there are currently 81 people but several are left out due to exclusion criteria. I'll send it to you when we have more participants."

[ANÓNIMOS Prueba del Instrumento.xlsx](https://github.com/langcog/wordbank/files/7400084/ANONIMOS.Prueba.del.Instrumento.xlsx)

**Comment by HenryMehta** [comment]
@mcfrank I am unable to open this file

**Comment by mcfrank** [comment]
[ANONIMOS.Prueba.del.Instrumento.xls](https://github.com/langcog/wordbank/files/8312963/ANONIMOS.Prueba.del.Instrumento.xls)
Here is an .XLS version of the file, but I can open the attached XLSX in Mac Excel 16.59. Can you tell me what the error is? 

One issue is that there is a different worksheet for every child  I believe...

**Comment by HenryMehta** [comment]
@mcfrank I can open the new file so all good from that POV.  Not sure about the data though.  I'm going to put this to bottom of the pile

**Comment by mcfrank** [comment]
Sounds right!

Mike

**Comment by alvinwmtan** [comment]
I've tidied all the data into the correct specs; this should be loadable now:

[[Spanish_Chilean_WG].csv](https://github.com/langcog/wordbank/files/8535891/Spanish_Chilean_WG.csv)
[SpanishChileanWG_Navarro_Pilot_data.csv](https://github.com/langcog/wordbank/files/8535892/SpanishChileanWG_Navarro_Pilot_data.csv)
[SpanishChileanWG_Navarro_Pilot_fields.csv](https://github.com/langcog/wordbank/files/8535894/SpanishChileanWG_Navarro_Pilot_fields.csv)
[SpanishChileanWG_Navarro_Pilot_values.csv](https://github.com/langcog/wordbank/files/8535895/SpanishChileanWG_Navarro_Pilot_values.csv)

(Documentation for the relabelling can be found here:)
[Spanish (Chilean) notes.xlsx](https://github.com/langcog/wordbank/files/8535896/Spanish.Chilean.notes.xlsx)

**Comment by HenryMehta** [comment]
@alvinwmtan 

`chocale` is used twice.  item_266 and item_472 within the `[Spanish_Chilean_WG].csv` file and twice in the `_data.csv` file so when I try and load the data it is only recognising the first item and a response of `no` causes a crash

**Comment by HenryMehta** [comment]
@alvinwmtan deployed just now.  I had to change the fields file to use the categories rather than always looking up on 'word'

**Comment by alvinwmtan** [comment]
@HenryMehta sorry, found a few more duplicate items which are now disambiguated

[[Spanish_Chilean_WG].csv](https://github.com/langcog/wordbank/files/8557124/Spanish_Chilean_WG.csv)
[SpanishChileanWG_Navarro_Pilot_data.csv](https://github.com/langcog/wordbank/files/8557125/SpanishChileanWG_Navarro_Pilot_data.csv)
[SpanishChileanWG_Navarro_Pilot_fields.csv](https://github.com/langcog/wordbank/files/8557126/SpanishChileanWG_Navarro_Pilot_fields.csv)
[SpanishChileanWG_Navarro_Pilot_values.csv](https://github.com/langcog/wordbank/files/8557127/SpanishChileanWG_Navarro_Pilot_values.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan deployed

**Comment by alvinwmtan** [comment]
@HenryMehta great, all good from R!

**Comment by alvinwmtan** [comment]
> No paper, cite to "Sergio Muñoz Navarro and Luis Leonardo Cepeda Guíñez"

@HenryMehta could you add this for contributor?
