### ISSUE TITLE
some Spanish (Mexican) WS and WG datasets ("source_name") incorrect

### ISSUE THREAD

**Issue by kachergis** [langcog/wordbank#234]
"Fernald (Outreach)" is not a valid name for Mexican Spanish WG or WS data (should be "Fernald (SLENA)", I think). I don't think the incorrect dataset label is in any of the raw data (CSVs) or the file names, so I'm guessing it was incorrectly entered when running the python import script?

**Comment by alvinwmtan** [comment]
@HenryMehta I think this is okay
