### ISSUE TITLE
peruvian spanish

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#237]
A few notes:  
-age is shown in months 
-for sex: 1 = girl, 2 = boy 
-all vocabulary item labels show word (as shown in the CDI form) / word class / CDI category (this is all in Spanish) 
-for all vocabulary items: 0 means no (no "doesn´t understand" for receptive vocabulary and "doesn´t produce" for expressive vocabulary) and 1 means yes  
-in the case of the 8-15 month-olds since the CDI gives parents 3 possible answers (nothing, understands, and understands and produces), we calculated understanding inferring comprehension from production too. So a child whose parent reports she says a specific word, is considered to also understand it. 

| Number of items | Number of children
-- | -- | --
16-30 months_produces.xlsx | 600 | 105 (46 girls)

8-15 months_produces.xlsx | 343 | 87 (46 girls)
8-15 months_understands.xlsx | 343 | 87 (46 girls)

[8-15 months_understands.xlsx](https://github.com/langcog/wordbank/files/7952600/8-15.months_understands.xlsx)
[16-30 months_produces.xlsx](https://github.com/langcog/wordbank/files/7952602/16-30.months_produces.xlsx)
[8-15 months_produces.xlsx](https://github.com/langcog/wordbank/files/7952606/8-15.months_produces.xlsx)

**Comment by mcfrank** [comment]
A non commercial license for this one!

REFERENCES:

Blume, M., Fernández-Flecha, M., Junyent, A., & Tijero, T. (2019). Proceso de adaptación de los Inventarios de Desarrollo Comunicativo MacArthur-Bates al castellano estándar del Perú [Adaptation process of the MacArthur-Bates Communicative Development Inventories to Standard Peruvian Spanish]. Lexis, 43(2), pp. 369-420. https://doi.org/10.18800/lexis.201902.003

Fernández-Flecha, M., Blume, M., Junyent, A., & Tijero, T. (2021). Gesture development in Peruvian children and its relationship
with vocalizations and vocabulary. Gesture, 20(1), pp. 1-29. https://doi.org/10.1075/gest.18010.fer

Fernández-Flecha, M., Junyent, A., & Blume, M. (2021). ¿Qué comprenden y dicen los niños peruanos en la primera infancia? Resultados preliminares de tamaño y composición del vocabulario entre los 8 y los 30 meses de edad [What do Peruvian children understand and say in early childhood? Preliminary results on vocabulary size and composition between 8 and 30 months of age]. Lexis, V(2), 729-764. https://doi.org/10.18800/lexis.202102.007

Junyent, A., Fernández-Flecha, M., Blume, M., & Tijero, T. (2020). Vocabulario y gramática en el castellano peruano infantil [Productive vocabulary and its relationship with grammar in Peruvian-Spanish-speaking children between 16 and 30 months of age]. Interdisciplinaria. Revista de Psicología y Ciencias Afines, 37(2), pp. 143-158. https://doi.org/10.16888/interd.2020.37.2.9

**Comment by HenryMehta** [comment]
@mcfrank Are IDs unique to the file, or are IDs across files the same child but different administrations?

**Comment by mcfrank** [comment]
I believe that:
* both 8-15 month files are the same - the IDs are the same and they are actually just the two response types (understands and produces). In other words, row 2 of each file represents two different "views" of the same administration. 
* IDs are distinct across the 8-15 and 16-30, representing different kids. 
* column 3 of 16-30 is gender/sex.

**Comment by alvinwmtan** [comment]
Tidied files:
[[Spanish_Peruvian_WG].csv](https://github.com/langcog/wordbank/files/8542940/Spanish_Peruvian_WG.csv)
[[Spanish_Peruvian_WS].csv](https://github.com/langcog/wordbank/files/8542941/Spanish_Peruvian_WS.csv)
[SpanishPeruvianWG_Blume_data.csv](https://github.com/langcog/wordbank/files/8542942/SpanishPeruvianWG_Blume_data.csv)
[SpanishPeruvianWG_Blume_fields.csv](https://github.com/langcog/wordbank/files/8542943/SpanishPeruvianWG_Blume_fields.csv)
[SpanishPeruvianWG_Blume_values.csv](https://github.com/langcog/wordbank/files/8542944/SpanishPeruvianWG_Blume_values.csv)
[SpanishPeruvianWS_Blume_data.csv](https://github.com/langcog/wordbank/files/8542945/SpanishPeruvianWS_Blume_data.csv)
[SpanishPeruvianWS_Blume_fields.csv](https://github.com/langcog/wordbank/files/8542946/SpanishPeruvianWS_Blume_fields.csv)
[SpanishPeruvianWS_Blume_values.csv](https://github.com/langcog/wordbank/files/8542947/SpanishPeruvianWS_Blume_values.csv)

**Comment by HenryMehta** [comment]
> A non commercial license for this one!

What does this mean for the licence field?  All licenses seem to be `CC-BY`

**Comment by HenryMehta** [comment]
@alvinwmtan these are now loaded

**Comment by alvinwmtan** [comment]
> > A non commercial license for this one!
> 
> What does this mean for the licence field? All licenses seem to be `CC-BY`

I believe it's [CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0/)

**Comment by alvinwmtan** [comment]
@HenryMehta looks good from R!
