### ISSUE TITLE
Unicode Encoding in wordbank2

### ISSUE THREAD

**Issue by JMankewitz** [langcog/wordbank#238]
Hi Henry! 

I'm testing the new wordbank2 database and am having trouble figuring out the correct unicode encoding. The data looks pretty good when using mysql, but we see issues (see below) when pulling data using the R database reader (which works fine with the original wordbank db). I've attached an example. 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/8647029/153334781-3a464920-5236-4839-b5f4-b98fe0420369.png">

Thanks!

**Comment by mikabr** [comment]
moving this to `wordbankr`

**Comment by alvinwmtan** [comment]
@mikabr seems to not be fixed? pulling e.g. Russian data or info on datasets still produces ??? and <e1> (etc.) for me

**Comment by mikabr** [comment]
are you sure you're on the latest version of wordbankr? the `connect_to_workbank()` function should have encoding-related db queries if so.

**Comment by alvinwmtan** [comment]
@mikabr ah sorry i hadn't updated, my bad
