### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#239]
we would like to have a versioning system for the WB database. our solution is to save periodic named snapshots of the database and to try to minimize updates in between these so that people can never to these updates. 

summarizing our discussions: 
- we will put WB1 as a SQL dump in an S3 bucket (@HenryMehta is this easy for you to do?)
- we will finish WB2 updates and data imports, and names this 2022.1 and put it also in an S3 bucket

**Comment by HenryMehta** [comment]
@mcfrank You can just take manual snapshots of an RDS database and store them as snapshots in the RDS area.  They are easy to recover to a new RDS database from there

**Comment by mcfrank** [comment]
@JMankewitz will add the documentation via a PR
