### ISSUE TITLE
add field for longitudinal administration

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#24]
when importing data, we should figure out which administrations are for the same kid (probably by assuming that study_id + kid_id maps uniquely to a kid) and labeling which administration that is for the kid (first, second, etc. by age)

**Comment by mcfrank** [comment]
Note to tell Mark Applebaum at UCSD when we do this - he is interested.

**Comment by mikabr** [comment]
We've figured out a way for this functionality to be provided without changing import/data structure.
