### ISSUE TITLE
catalan data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#240]
From Isabel Serrat
```
Here I attach the spps file of the Catalan MCB-CDI-I with the data of the variables sex, age in months, birth order, number of siblings, mother's educational level and bilingualism.
 
Note about one participant in the template: 
We detected two participants with the same number (id 581). We do not know what could have happened, but we only have one questionnaire that corresponds to that number. If we do not know what happened, we will have to delete the information about that participant. I will let you know which one it is.
 ```
[Plantilla variables CDI-I Wordbank maig 22.sav.zip](https://github.com/langcog/wordbank/files/8327046/Plantilla.variables.CDI-I.Wordbank.maig.22.sav.zip)

@vmarchman maybe you can convert from SAV and reupload?

**Comment by vmarchman** [comment]
Here are the definitions:

Sex: (sexe)

1 = nena = girl
2 = nen = boy

Birth order (order_naixement):

1 = first,
2 = second,
3 = third
4 = later

Bilingualism (MonoBiling): (not sure what exactly these definitions mean)

1 = monolingual
2 = "family bilingualism" (bilinguisme familiar)
3 = "other bilingualisms" (Altres bilinguismes)

Maternal Education (escola_mare):

1 = without schooling
2 = primary
3 = secondary
4 = university

**Comment by HenryMehta** [comment]
This is the data as a csv file

[output.csv](https://github.com/langcog/wordbank/files/8349988/output.csv)

**Comment by HenryMehta** [comment]
Actually, I don't think this can be the data because it is only the child info rather than the administration responses

**Comment by mcfrank** [comment]
oops - we need to get the scans rekeyed!
https://drive.google.com/drive/u/1/folders/1l3ZBAAu1UxeWHvg5kuMuV_903VCLXpy-

**Comment by alvinwmtan** [comment]
WG: 
[[Catalan_WG].csv](https://github.com/langcog/wordbank/files/12213563/Catalan_WG.csv)
[CatalanWG_Serrat_data.csv](https://github.com/langcog/wordbank/files/12213565/CatalanWG_Serrat_data.csv)
[CatalanWG_Serrat_fields.csv](https://github.com/langcog/wordbank/files/12213568/CatalanWG_Serrat_fields.csv)
[CatalanWG_Serrat_values.csv](https://github.com/langcog/wordbank/files/12213569/CatalanWG_Serrat_values.csv)
The demographics for child 581 were taken from the first entry in the metadata (there are two entries as noted above)

WS pending rekeying

**Comment by alvinwmtan** [comment]
@mcfrank Not sure how much we want to dive into this, but in the WS, the file labelled `545-558_bo.pdf` appears to have child IDs 545, 557, and then 507–517 (which are duplicated from the file `500-517.pdf`). Maybe send an email to the contributor to ask if they have the original scan? (If not I'll discard the duplicates)

**Comment by alvinwmtan** [comment]
[[Catalan_WS].csv](https://github.com/langcog/wordbank/files/12821904/Catalan_WS.csv)
[CatalanWS_Serrat_data.csv](https://github.com/langcog/wordbank/files/12821905/CatalanWS_Serrat_data.csv)
[CatalanWS_Serrat_fields.csv](https://github.com/langcog/wordbank/files/12821906/CatalanWS_Serrat_fields.csv)
[CatalanWS_Serrat_values.csv](https://github.com/langcog/wordbank/files/12821907/CatalanWS_Serrat_values.csv)
[Catalan_notes.md](https://github.com/langcog/wordbank/files/12821908/Catalan_notes.md)

Missing scans ignored; remaining WS data as above

**Comment by HenryMehta** [comment]
@alvinwmtan 
What are contributor and citation for this dataset?

**Comment by HenryMehta** [comment]
@alvinwmtan Line 48 has an age of NA.  We cannot import this record without a valid age.  What would you like me to do?

**Comment by mcfrank** [comment]
Guessing it's: https://www.torrossa.com/en/resources/an/5155491

Mike

**Comment by HenryMehta** [comment]
@alvinwmtan deployed to dev for testing

**Comment by alvinwmtan** [comment]
> WG: [[Catalan_WG].csv](https://github.com/langcog/wordbank/files/12213563/Catalan_WG.csv) [CatalanWG_Serrat_data.csv](https://github.com/langcog/wordbank/files/12213565/CatalanWG_Serrat_data.csv) [CatalanWG_Serrat_fields.csv](https://github.com/langcog/wordbank/files/12213568/CatalanWG_Serrat_fields.csv) [CatalanWG_Serrat_values.csv](https://github.com/langcog/wordbank/files/12213569/CatalanWG_Serrat_values.csv) The demographics for child 581 were taken from the first entry in the metadata (there are two entries as noted above)
> 
> WS pending rekeying

@HenryMehta could you also deploy the WG? Thanks!

**Comment by HenryMehta** [comment]
@alvinwmtan sorry, missed it.  Deployed to dev now

**Comment by alvinwmtan** [comment]
@HenryMehta WG looks good. For WS, I realised that we should be using the "edat" column, not "age"—this should have much fewer NAs.

**Comment by HenryMehta** [comment]
@alvinwmtan It is already using edat

**Comment by alvinwmtan** [comment]
@HenryMehta hmm, in that case there should be 859 administrations, not 605 (which it is currently)

**Comment by HenryMehta** [comment]
@alvinwmtan There are 605 rows in the data file

**Comment by alvinwmtan** [comment]
@HenryMehta this file has 866; perhaps you manually filtered out those with _age_ NA and not _edat_ NA?
> [CatalanWS_Serrat_data.csv](https://github.com/langcog/wordbank/files/12821905/CatalanWS_Serrat_data.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan Those without an age cannot be loaded so I deleted from dataset

**Comment by alvinwmtan** [comment]
@HenryMehta yes—those without `edat` should be deleted (not those without the column labelled `age`, which is not in fact the `data_age` column for this dataset)

**Comment by HenryMehta** [comment]
@alvinwmtan deployed

**Comment by alvinwmtan** [comment]
@HenryMehta looks good now, thanks!
