### ISSUE TITLE
ASL CDI 2.0

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#241]
Here are data from a new ASL (american sign language) instrument, the ASLI CDI 2.0. 

Citation: `Caselli, N., Lieberman, A., Pyers, J. (2020). The ASL-CDI 2.0: An updated, normed adaptation of the MacArthur Bates Communicative Development Inventory for American Sign Language. Behavior Research Methods.`

From Naomi Caselli:
```
All the kids in this sample are deaf or hard of hearing, and have at least one deaf parent. None reported any additional diagnoses that could affect language or are blind. Some kids participated twice. Each child is identified by a Child ID, and each report is identified by a SessionID. 

We show videos for each sign, rather than just an English translation. That means I don't have a traditional form to share with you, since the whole thing is administered online. Instead, you can see the attached list of items, and a video for each item. It also means that the form is really long (it takes ~3 hours to complete), and so not all parents finish the whole form. To account for this, we typically calculate scores in proportions rather than counts. The data here only include items that the parents responded to (i.e., there are different numbers of items for each report). 

In getting the data for you, I found an error. There is one item that showed up on the form twice (the sign is THINK). 

I don't have birth order. We do have a bunch of stuff on language backgrounds, but I am hesitant to include it because this population is so small that I don't want to inadvertently make the participants identifiable. If there is something specific that would be helpful, let me know.

```

[ASLCDI_normative_data.csv](https://github.com/langcog/wordbank/files/8327194/ASLCDI_normative_data.csv)
[Sign_list.csv](https://github.com/langcog/wordbank/files/8327195/Sign_list.csv)

**Comment by HenryMehta** [comment]
This file is the data converted into a data file we can use

[asl_Caselli_cdi1_data.csv](https://github.com/langcog/wordbank/files/8361811/asl_Caselli_cdi1_data.csv)

**Comment by HenryMehta** [comment]
This is form definition file - I do not know what uni-lemmas or gloss to use so would be helpful if someone could edit
[[asl_cdi2].csv](https://github.com/langcog/wordbank/files/8361910/asl_cdi2.csv)

**Comment by HenryMehta** [comment]
this is the fields file

[asl_Caselli_cdi2_fields.csv](https://github.com/langcog/wordbank/files/8362036/asl_Caselli_cdi2_fields.csv)

**Comment by HenryMehta** [comment]
And here is the values file.  I shall try loading these tomorrow so if anyone fancies checking them today that would be great

[asl_Caselli_cdi2_values.csv](https://github.com/langcog/wordbank/files/8362156/asl_Caselli_cdi2_values.csv)

**Comment by HenryMehta** [comment]
@mcfrank I've now deployed this to wordbank2 if anyone would like to check over the data

**Comment by alvinwmtan** [comment]
Hi @HenryMehta, I'm getting this error:
```
Table 'wordbank.instruments_american_sign_language_cdi2' doesn't exist
```
Is the table called something else in wordbank2?

**Comment by HenryMehta** [comment]
It is called

`wordbank.instruments_american_sign_language_cdi`

**Comment by alvinwmtan** [comment]
@HenryMehta Would it be possible to rename the table `wordbank.instruments_american_sign_language_cdi2`? We currently make assumptions about what the instrument table is called that are broken by this mismatch

**Comment by HenryMehta** [comment]
@alvinwmtan I've amended to `wordbank.instruments_american_sign_language_cditwo` and amended the form to `CDITwo`.  If I didn't do both Django would revert it to CDI (it won't use number in the table names) when we add a new form or language.

I've not reloaded anything else.  I think it should work but I might need to delete and reload the existing datasets

**Comment by alvinwmtan** [comment]
@HenryMehta I can't seem to pull the table from R

**Comment by HenryMehta** [comment]
I can see the database table in the database so I don't know why you cannot pull it

![image](https://user-images.githubusercontent.com/10542767/162898856-331bc472-5c44-4bf3-b055-9226242e64fd.png)

**Comment by alvinwmtan** [comment]
@HenryMehta Okay I can actually pull from this table; I think the issue is that the administrations table doesn't contain any administrations for this instrument (no entries with `instrument_id == 74`)

**Comment by HenryMehta** [comment]
@alvinwmtan ok - that should be sorted now.  I needed to reload the data

**Comment by alvinwmtan** [comment]
Hi @HenryMehta, the instrument table now contains 3 sets of (what I suppose is supposed to be) the same data, and the set that corresponds to the data_ids in the administrations table only has blanks for value (which is wrong). We may need to delete the entire instrument table and reload this data.

**Comment by HenryMehta** [comment]
@alvinwmtan 
I only see ASL CDITwo once in the instrument table, as id 74 and I see the administrations linked to it so I don't understand what you're meaning.

If I delete the whole instrument (I assume you mean `common_instrument`) table then I would need to delete the whole database and start again.  But I now realised you might mean `instuments_american_sign_languages_cditwo`   Is that what you mean, do you want me to delete `instuments_american_sign_languages_cditwo` and reload the dataset?

**Comment by alvinwmtan** [comment]
@HenryMehta Yup I meant `instruments_american_sign_languages_cditwo` (which is the table that seems to have 3 times of the same dataset). Hopefully that's not too much of a hassle

**Comment by HenryMehta** [comment]
ok - will do it now

**Comment by HenryMehta** [comment]
@alvinwmtan try now

**Comment by HenryMehta** [comment]
@alvinwmtan done

**Comment by alvinwmtan** [comment]
@HenryMehta perfect, have pulled it from R and it looks good!

**Comment by HenryMehta** [comment]
@alvinwmtan could you quickly check this again.  I found something strange when sorting the Resches and fixed what I found at the same time.  I just to to make sure I didn't cause a different issue

**Comment by alvinwmtan** [comment]
@HenryMehta the instrument table is present, but the dataset is missing from `common_dataset` and the administrations are missing from `common_administration`

**Comment by HenryMehta** [comment]
ok - I'm in Greece at the moment so I'll pick up at some point tomorrow

**Comment by HenryMehta** [comment]
@alvinwmtan that should be sorted now

**Comment by alvinwmtan** [comment]
@HenryMehta all good now!
