### ISSUE TITLE
Hungarian WS in Master but not Wordbank2

### ISSUE THREAD

**Issue by HenryMehta** [langcog/wordbank#243]
Today I merged master into Wordbank2 to ensure Wordbank2 is up to date.

This created an Hungarian_WS dataset within raw_data, but it doesn't seem to have ever been made into tables or the dataset added.
I've added the dataset to Wordbank2 and I shall now attempt to load the data

**Comment by HenryMehta** [comment]
@JMankewitz @alvinwmtan 
I've now loaded this data into Wordbank2

**Comment by alvinwmtan** [comment]
@HenryMehta Pulled from R; looks good to go

**Comment by alvinwmtan** [comment]
citations: 

Kas, B., Lőrik, J., Sz. Vékony, A., K. Kasziba, H. (2010). A korai nyelvi fejlődés új vizsgálóeszköze, a MacArthur-Bates Kommunikatív Fejlődési Adattár (KOFA) bemutatása és validitási vizsgálata. Gyógypedagógiai Szemle, 38, 114-125.
http://www.epa.hu/03000/03047/00049/pdf/EPA03047_gyosze_2010_2_114-125.pdf

Kas, B., Lőrik, J., & Bertalan, R. F. (2017). A korai nyelvi‐kommunikációs fejlettség új mérőeszköze, a MacArthur‐Bates Kommunikatív Fejlődési Adattár 3.(KOFA–3) alapjai és gyakorlati alkalmazási lehetőségei. Logopédia, 2(1), 41-56.
http://real.mtak.hu/72617/1/Logopedia_2017_1_u.pdf

Kas, B., Jakab, Z., & Lőrik, J. (2022). Development and norming of the Hungarian CDI‐III: A screening tool for language delay. International Journal of Language & Communication Disorders, 57(2), 252-273.
https://onlinelibrary.wiley.com/doi/full/10.1111/1460-6984.12686

**Comment by HenryMehta** [comment]
@alvinwmtan You've given me 3 citations but there is only 1 dataset so which should I use?

**Comment by HenryMehta** [comment]
done
