### ISSUE TITLE
add documentation page to website

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#244]
we can move content from the sidebar of the about page, including wordbankr tutorial, github links to wordbank and wordbankr, and add the unilemma policy as a subpage (plaintext): https://docs.google.com/document/d/1XfH5HQ61xj_tntzdwC4Md1FvLF-wwfpVMGVWtpOwylM/edit

**Comment by mcfrank** [comment]
maybe it should look like this: https://langcog.github.io/peekbank-website/docs/documentation/

with the first section being "Getting data from wordbank using wordbankr" and some text and then the second section being "cross linguistic mappings" and some text and a link to the policy?

**Comment by mikabr** [comment]
do we still want to do this?

**Comment by mcfrank** [comment]
# Accessing data from Wordbank

Our shiny apps allow analyses of normative growth in vocabulary size and individual item trajectories. They also allow for download of several forms of tabular data. These apps cover some of the most common use cases for Wordbank data but not all.

In addition to the apps available through the analysis page, you can access wordbank data from [wordbankr](link to CRAN), our R API package. There is a data access tutorial for wordbankr available here: LINK. The R API is the most flexible way to work with data from the database. 

If you are interested in item- and group-related analyses of the Wordbank data that are not available through the shiny apps, it may also be helpful to identify the relevant analysis in the [Wordbank book](http://wordbank-book.stanford.edu) and look at the [code for those analyses on github](http://github.com/langcog/wordbank-book).

# About Wordbank infrastructure

Wordbank is a [MySQL](https://www.mysql.com/) database and [Django](https://www.djangoproject.com/) frontend, with interactive reports created using [Shiny](http://shiny.rstudio.com/), an R platform for the web. All of the source code is open and available at [github](https://github.com/langcog/wordbank).

# Accessing previous versions of Wordbank

ADD DOCUMENTATION HERE
