### ISSUE TITLE
cache vocabulary sizes

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#245]
for the datasets in wordbank2, vocabulary sizes need to be cached in the administrations table using the django command [`populate_vocabulary_size`](https://github.com/langcog/wordbank/blob/master/common/management/commands/populate_vocabulary_size.py) ([see here](https://github.com/langcog/wordbank/wiki/How-to-import-a-new-instrument-and-dataset))
@HenryMehta

**Comment by HenryMehta** [comment]
@mikabr done

**Comment by mcfrank** [comment]
Thanks! This is great. We will probably have to rerun when we are
completely done with the dataset import project, but we needed it to
develop against in the shiny apps rewrite now.

Is there a way to integrate this migration into the deployment workflow for
new datasets?

thanks

**Comment by HenryMehta** [comment]
@mcfrank The process is manual and the problem is I keep forgetting to run it (even though the instructions I've written tell me to run it!).  I could include this within the previous command but it would still be a manual process until that point
