### ISSUE TITLE
Add Edgin special population data

### ISSUE THREAD

**Issue by vmarchman** [langcog/wordbank#247]
Import data for special populations from Edgin lab.  
[EdginLab_DemographicData_WordBank.csv](https://github.com/langcog/wordbank/files/8584387/EdginLab_DemographicData_WordBank.csv)
[EdginLab_WG.csv](https://github.com/langcog/wordbank/files/8584388/EdginLab_WG.csv)
[EdginLab_WS.csv](https://github.com/langcog/wordbank/files/8584390/EdginLab_WS.csv)

@alvinwmtan Could you help make sure that files are in appropriate format for import?

**Comment by mcfrank** [comment]
Edgin, J. O., Tooley, U., Demara, B., Nyhuis, C., Anand, P., & Spanò, G. (2015). Sleep disturbance and expressive language development in preschool‐age children with Down syndrome. Child Development, 86(6), 1984-1998.

**Comment by alvinwmtan** [comment]
Cleaned data:
[EnglishWG_Edgin_data.csv](https://github.com/langcog/wordbank/files/8894856/EnglishWG_Edgin_data.csv)
[EnglishWG_Edgin_fields.csv](https://github.com/langcog/wordbank/files/8894857/EnglishWG_Edgin_fields.csv)
[EnglishWG_Edgin_values.csv](https://github.com/langcog/wordbank/files/8894858/EnglishWG_Edgin_values.csv)
[EnglishWG_Edgin_notes.txt](https://github.com/langcog/wordbank/files/8894859/EnglishWG_Edgin_notes.txt)

[EnglishWS_Edgin_data.csv](https://github.com/langcog/wordbank/files/8894861/EnglishWS_Edgin_data.csv)
[EnglishWS_Edgin_fields.csv](https://github.com/langcog/wordbank/files/8894862/EnglishWS_Edgin_fields.csv)
[EnglishWS_Edgin_values.csv](https://github.com/langcog/wordbank/files/8894863/EnglishWS_Edgin_values.csv)
[EnglishWS_Edgin_notes.txt](https://github.com/langcog/wordbank/files/8894864/EnglishWS_Edgin_notes.txt)

@HenryMehta for children with no health conditions (coded '0'), I left the "conditions" value blank; let me know if this works!

**Comment by HenryMehta** [comment]
@alvinwmtan I've deployed Edgin WG.  Let me know how that looks.  I'll get onto WS later today or later this week

**Comment by HenryMehta** [comment]
@alvinwmtan Edgin WS now loaded

**Comment by alvinwmtan** [comment]
@HenryMehta looks good from R
