### ISSUE TITLE
Floccia bilingual data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#251]
Datafile contains
[wordbank data.xlsx](https://github.com/langcog/wordbank/files/8732059/wordbank.data.xlsx)

Contains data on bilinguals for 100 word oxford CDI  (production/comprehension) plus 30 words across various languages. 

probably needs some codebook support on momed and other fields (or we can try to back this out of the monograph)

**Comment by mcfrank** [comment]
Our decision is to import JUST the oxford CDI words (not the 30 extra words) and to mark the language background appropriately for these kids. @kachergis might just use the 30 extras for swadesh validation.

**Comment by alvinwmtan** [comment]
Policy for short forms: 
- Import as **new instrument** (avoids inaccurate renderings of children's vocabulary sizes if pulling long form), with "Short" appended to the instrument name
- `item_id`s follow long form (i.e., are not sequential in short forms)

**Comment by alvinwmtan** [comment]
@HenryMehta cleaned files are here:

[[EnglishBritishOxfordShort].csv](https://github.com/langcog/wordbank/files/8971221/EnglishBritishOxfordShort.csv)
[EnglishBritishOxfordShort_Floccia_data.csv](https://github.com/langcog/wordbank/files/8971222/EnglishBritishOxfordShort_Floccia_data.csv)
[EnglishBritishOxfordShort_Floccia_fields.csv](https://github.com/langcog/wordbank/files/8971223/EnglishBritishOxfordShort_Floccia_fields.csv)
[EnglishBritishOxfordShort_Floccia_values.csv](https://github.com/langcog/wordbank/files/8971224/EnglishBritishOxfordShort_Floccia_values.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan is the form_type for OxfordShort WS or WG as defined in #258 ?

**Comment by alvinwmtan** [comment]
@HenryMehta it should be WG—thanks for flagging

**Comment by HenryMehta** [comment]
@alvinwmtan Available to test

**Comment by alvinwmtan** [comment]
@HenryMehta looks good from R

**Comment by alvinwmtan** [comment]
citation is: Floccia, C., Sambrook, T. D., Luche, C. D., Kwok, R., Goslin, J., White, L., Cattani, A., Sullivan, E., Abbot-Smith, K., Krott, A., Mills, D., Rowland, C., Gervain, J., Plunkett, K., Hoff, E., & Bauer, P. J. (2018). Vocabulary of 2-year-olds learning English and an additional language: Norms and effects of linguistic distance. Monographs for the Society for Research in Child Development, 83(1), 1–235. https://doi.org/10.1111/mono.12352
