### ISSUE TITLE
Finnish data

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#252]
From #232 – data to look at in the future:

[Finnish.Long.form.versions.of.the.CDI_.WG._.at.12.and.at.15.months.of.age._.Expressive.words.csv](https://github.com/langcog/wordbank/files/8734629/Finnish.Long.form.versions.of.the.CDI_.WG._.at.12.and.at.15.months.of.age._.Expressive.words.csv)
[Finnish.Short.form.versions.of.the.CDI._.Toddler.version._.at.18.and.at.24.months._.Expressive.words.csv](https://github.com/langcog/wordbank/files/8734630/Finnish.Short.form.versions.of.the.CDI._.Toddler.version._.at.18.and.at.24.months._.Expressive.words.csv)
[Finnnish.Short.form.versions.of.the.CDI._.Infant.version._.at.9.12.15.18.months._.Expressive.words.csv](https://github.com/langcog/wordbank/files/8734631/Finnnish.Short.form.versions.of.the.CDI._.Infant.version._.at.9.12.15.18.months._.Expressive.words.csv)

WG: only contains production values (no comprehension)
Short forms: to return to in the future

**Comment by alvinwmtan** [comment]
Note: WS Short Form resolved in #262; pending WG data updates

**Comment by alvinwmtan** [comment]
WG Production: 
[[FinnishWGProd].csv](https://github.com/langcog/wordbank/files/12521909/FinnishWGProd.csv)
[[FinnishWGProdShort].csv](https://github.com/langcog/wordbank/files/12521911/FinnishWGProdShort.csv)
[FinnishWGProd_Stolt_data.csv](https://github.com/langcog/wordbank/files/12521912/FinnishWGProd_Stolt_data.csv)
[FinnishWGProd_Stolt_fields.csv](https://github.com/langcog/wordbank/files/12521913/FinnishWGProd_Stolt_fields.csv)
[FinnishWGProd_Stolt_values.csv](https://github.com/langcog/wordbank/files/12521914/FinnishWGProd_Stolt_values.csv)
[FinnishWGProdShort_Stolt_data.csv](https://github.com/langcog/wordbank/files/12521915/FinnishWGProdShort_Stolt_data.csv)
[FinnishWGProdShort_Stolt_fields.csv](https://github.com/langcog/wordbank/files/12521916/FinnishWGProdShort_Stolt_fields.csv)
[FinnishWGProdShort_Stolt_values.csv](https://github.com/langcog/wordbank/files/12521917/FinnishWGProdShort_Stolt_values.csv)

Note that these forms are production-only.

**Comment by HenryMehta** [comment]
@alvinwmtan should there be WG and WGShort or should they also include Prod?

**Comment by alvinwmtan** [comment]
@HenryMehta they include prod because these are prod-only forms (whereas normal WGs have both prod and comp); we decided to make new forms so they wouldn't be confused with the existing forms

**Comment by alvinwmtan** [comment]
@HenryMehta Fixed:

[[FinnishWGProd].csv](https://github.com/langcog/wordbank/files/13669266/FinnishWGProd.csv)
[[FinnishWGProdShort].csv](https://github.com/langcog/wordbank/files/13669267/FinnishWGProdShort.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan I still have an issue with [FinnishWGProd_Stolt_fields.csv](https://github.com/langcog/wordbank/files/12521913/FinnishWGProd_Stolt_fields.csv)

**Comment by alvinwmtan** [comment]
@HenryMehta Try this:
[FinnishWGProd_Stolt_fields.csv](https://github.com/langcog/wordbank/files/13676089/FinnishWGProd_Stolt_fields.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan deploying to dev now

**Comment by alvinwmtan** [comment]
Citation: Stolt, S. & Vehkavuori, S-M. 2018. Sanaseula. Finnish short form versions of the MacArthur Communicative Development Inventories. Jyväskylä: Niilo Mäki Instituutti.

Contributor: Suvi Stolt, University of Helsinki.
