### ISSUE TITLE
Error in Kigiriama data

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#257]
In KigiriamaWG_Alcock_data.csv, sno ITS020 has age -3; should be 9.

**Comment by HenryMehta** [comment]
@alvinwmtan I have no record with sno ITS020 in that dataset

**Comment by alvinwmtan** [comment]
@HenryMehta It's [this record](https://github.com/langcog/wordbank/blob/wordbank2/raw_data/Kigiriama_WG/KigiriamaWG_Alcock_data.csv#L31)

**Comment by HenryMehta** [comment]
@alvinwmtan sorry - I was looking at Kiswahili (for no good reason).  Re-importing with correction now
