### ISSUE TITLE
form_type needs to be populated

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#258]
The field `form_type` in the instrument table is currently empty; this needs to be populated with correct values.

**Comment by HenryMehta** [comment]
@alvinwmtan What should be in it?

**Comment by alvinwmtan** [comment]
@HenryMehta form_type data here:
[instruments.csv](https://github.com/langcog/wordbank/files/8971895/instruments.csv)
Note that this doesn't include the new short forms that are pending import, although these should straightforwardly follow their long form version

**Comment by HenryMehta** [comment]
@alvinwmtan Done

**Comment by alvinwmtan** [comment]
@HenryMehta looks good, thanks!
