### ISSUE TITLE
Citations in database

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#259]
Some citations haven't been updated, and some have extra question marks or Unicode issues

**Comment by HenryMehta** [comment]
@alvinwmtan 

I cannot see any unicode issues.  Can you highlight for me.  

I know several citations and contributors are missing, but I don't think I was provided them with the dataset information so I don't know what to put in

**Comment by alvinwmtan** [comment]
@HenryMehta I've tagged you for the remaining citations in the relevant issues

When pulling from R, I see extra prepended question marks for: 
- Marchman_Outreach1_English (American)_WS
- Fernald_Outreach_Spanish (Mexican)_WG
- Fernald_Outreach_Spanish (Mexican)_WS
- Pae__Korean_WS
- Pae__Korean_WG
- Bergmann__French (French)_WG
- VonHolzen__French (French)_WG
- Cadime__Portuguese (European)_WG
- Karousou__Spanish (European)_WG

These have all question marks instead of characters:
- CLEX__Russian_WG
- CLEX__Russian_WS

And a variety have individual letters that aren't rendered correctly (e.g., accented letters or apostrophes), including (but probably not limited to):
- Marchman Dallas Bilingual
- CLEX__Turkish_WG
- CLEX__Turkish_WS
- Smolik__Czech_WS
- Karousou__Spanish (European)_WG
- Karousou__Spanish (European)_WS
- OToole_English_Irish_Bilingual_WS
- OToole_English_Irish_Bilingual_WG
- Blume_Blume_Spanish (Peruvian)_WG
- Blume_Blume_Spanish (Peruvian)_WS

**Comment by HenryMehta** [comment]
Then I think this is more likely a problem pulling into R.  If you look at the website (http://wordbank2-dev.gsffhcf4an.us-west-2.elasticbeanstalk.com/contributors), the text is coming through fine which means it is in UTF-8.

I generally find files from you are in Apple Macintosh format, rather than UTF-8.  Could that be the issue

**Comment by alvinwmtan** [comment]
@HenryMehta this is probably related to #238. I don't think it has to do with the Mac format, since the citations weren't sent via a file, so somewhere along the pipeline there are some encoding issues. This will probably need a bit more investigation (perhaps from someone with more SQL knowledge than me), so we may need to hold off on this for now (as we try to push towards launching WB2) since it's not critical.

**Comment by alvinwmtan** [comment]
fixed by #238
