### ISSUE TITLE
headers for shiny apps on wordbank2

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#261]
although the shiny apps on the "Analyses" page are cleaned up, when you click on a specific app, you still get a header with all the old reports etc. (tab bar). can we clean this up so the tabs are consistent with the analysis landing page?  

perhaps this is pulled in from some static file by https://github.com/langcog/wordbank/blob/master/templates/analyses.html

@HenryMehta I think this should be an easy fix.

**Comment by mikabr** [comment]
fixed it
