### ISSUE TITLE
Finnish WS Short Form

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#262]
Resolves Finnish WS Short data from #252, via policy from [#251](https://github.com/langcog/wordbank/issues/251#issuecomment-1164916692)

[[Finnish_WSShort].csv](https://github.com/langcog/wordbank/files/8971577/FinnishWSShort.csv)
[FinnishWSShort_Stolt_data.csv](https://github.com/langcog/wordbank/files/8971578/FinnishWSShort_Stolt_data.csv)
[FinnishWSShort_Stolt_fields.csv](https://github.com/langcog/wordbank/files/8971579/FinnishWSShort_Stolt_fields.csv)
[FinnishWSShort_Stolt_values.csv](https://github.com/langcog/wordbank/files/8971580/FinnishWSShort_Stolt_values.csv)

@HenryMehta would be great if you could help import these

**Comment by HenryMehta** [comment]
@alvinwmtan available to test. Can you give me contributor and citation please

**Comment by alvinwmtan** [comment]
Citation: Stolt, S. & Vehkavuori, S-M. 2018. Sanaseula. Finnish short form versions of the MacArthur Communicative Development Inventories. Jyväskylä: Niilo Mäki Instituutti.

Contributor: Suvi Stolt, University of Helsinki.

**Comment by alvinwmtan** [comment]
@HenryMehta looks good from R

**Comment by alvinwmtan** [comment]
[[FinnishWSShort].csv](https://github.com/langcog/wordbank/files/12521950/FinnishWSShort.csv)
Also corrected the category prepositions -> locations

**Comment by HenryMehta** [comment]
@alvinwmtan Same issue as #232. Do you want me to just copy the definition row so item and definition are the same?
