### ISSUE TITLE
factor demographic facet variables for reports

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#27]
we should factor out a selector so we can add facets for the demographic variables to each report in a uniform way

**Comment by mcfrank** [comment]
this is terrible coding practice, but I don't want to commit yet...

To make this work we would:
- need to have a default blank variable
- order factor levels appropraitely

for data, just add:

group_by_("age", input$demo) %>%
      filter_(interp("!is.na(x)", x = as.name(input$demo))) %>%

for the plot, add:

      facet_wrap(input$demo) + 

and add:

demos <- reactive({
    list("Birth order" = "birth.order", 
         "Ethnicity" = "ethnicity",
         "Sex" = "sex",
         "Mother's education" = "momed.level")
  })

and in UI.R

      uiOutput("demo_selector"),

**Comment by mcfrank** [comment]
OK, I got further with the norms report. This is linked in branch iss27 to issue #55 as well. 

* We now have good smoothing with `gcrq` albeit with awful code to create those smoothers. 
* Also has facet variables. 

I was defeated by selectize though - I can't get the facet variables to select appropriately for the particular dataset. There is some reactive thing that I don't understand.

**Comment by mcfrank** [comment]
for reports to be faceted by demographics, we need to have factor levels sorted (mostly just momed)

**Comment by mikabr** [comment]
The facet variable options list is now reactive to the instrument, and momed has correctly sorted factor levels.

**Comment by mcfrank** [comment]
Broken on prod? 

Mike

**Comment by mikabr** [comment]
I merged the branch into master and pushed it to prod, but it's not working for some mysterious reason (runs totally fine on my machine...), I'm investigating

**Comment by mikabr** [comment]
also runs fine on my machine pulling data from the server, so it's not an issue in the data

**Comment by mcfrank** [comment]
Package dependencies I bet - I had to add a bunch of stuff (e.g. gcrq, splines, lazyeval etc.)

Mike

**Comment by mikabr** [comment]
I installed the packages that get loaded in the script (lazyeval and quantregGrowth). Are there other hidden dependencies?

**Comment by mcfrank** [comment]
No, that should do it... hum. 

Mike

**Comment by mikabr** [comment]
The error that's happening is "subscript out of bounds", btw

**Comment by mcfrank** [comment]
what?  

no idea. sorry... 

Mike

**Comment by mikabr** [comment]
I updated packages such that every single loaded package is the same version on my machine and on the server, didn't help. If they're running the same code, pulling the same data, and using the same packages, I really don't understand what the difference could be...

**Comment by mcfrank** [comment]
have you checked the r version? gah. 

Mike

**Comment by mikabr** [comment]
I have R 3.1.2 on my machine, the server had 3.1.1 and then I upgraded it to 3.1.3 -- upgrading is really easy on ubuntu but rather difficult on OSX, but since both versions on the server caused the problem, I can't imagine that's the problem.

**Comment by mikabr** [comment]
and it works fine on the [dev server] (http://54.149.39.46:3838/norms_app/)

**Comment by mcfrank** [comment]
Omg. 

Mike

**Comment by mikabr** [comment]
works just fine on the shiny server in command line R

**Comment by mikabr** [comment]
YES it works now after the curve-fitting code rewrite

**Comment by mikabr** [comment]
the curves look slightly different... compare [dev](http://54.149.39.46:3838/norms_app/) and [prod](http://wordbank.stanford.edu/reports?id=norms_app), but I don't want to deal with predictQR ever again at the moment, so oh well :P

**Comment by mikabr** [comment]
jk, only works with all data, demo faceting still breaks it. but progress

**Comment by mikabr** [comment]
So getting back to this issue more generally -- demographic selectors are now implemented in the norms report and histogram report, but not in the item trajectory report. They're a fair amount harder to implement there, and more generally the nice factoring we were hoping for doesn't seem to be possible: each report requires a bunch of custom data manipulation code, with somewhat insane standard evaluation everywhere. I feel like it makes sense to hold off on trying to implement selectors for the trajectory report, and first 1) actually understand SE; 2) try to re-design the reports to be have cleaner, more reusable, factored out code.

**Comment by mcfrank** [comment]
That seems reasonable to me - with the caveat that factorization seems like a more important solution when each report did less. Now that we think that reports will have a lot more functionality for each one, standardization seems like less of an issue.

How are we going to learn more about standard evaluation? Should we read something together? Invite someone to talk to us?

Mike

**Comment by mikabr** [comment]
That's a good point, standardization does seem less important, but I think there's still some design improvements we could do that would make new reports easier to add, existing reports less of a mess, and all reports easier to debug (this is a possibly the most important change, debugging is horrible right now).

I was thinking I'd read Hadley's Advanced R book to get a better handle on both SE and some other topics.
