### ISSUE TITLE
Update contributor info on contributors' page

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#278]
The [contributors info](http://wordbank.stanford.edu/contributors) has some missing information about some of the contributors (full name and affiliation); these are to be added (I will provide the info). The Eric Walle citation is also absent.

**Comment by alvinwmtan** [comment]
Missing or incomplete contributors by language:
* ASL: Naomi Caselli, Boston University
* Cantonese: Thierry Nazzi, Université Paris Cité
* Dutch: Christina Bergmann, Max Planck Institute for Psycholinguistics
* English (American): Jamie Edgin, University of Arizona; Eric Walle, University of California, Merced; Erika Hoff, Florida Atlantic University; Sharon Armon-Lotem, Bar-Ilan University
* English (Irish): Ciara O'Toole, University College Cork
* Finnish: Suvi Stolt, University of Helsinki
* Hebrew: Sharon Armon-Lotem, Bar-Ilan University
* Hungarian: Bence Kas, Eötvös Loránd University
* Irish: Ciara O'Toole, University College Cork
* Persian: Yalda Kazemi, Isfahan University of Medical Sciences
* Spanish (Argentinian): Mariela Resches, National Scientific and Technical Research Council (CONICET)
* Spanish (Mexican): Erika Hoff, Florida Atlantic University
* Spanish (Peruvian): María Blume del Río, Pontificia Universidad Católica del Perú

I will still need to retrieve the Eric Walle citation, but the other contributors should have their names and institutions correct now.

**Comment by mcfrank** [comment]
Do you want me to write to these folks for citation info?

**Comment by alvinwmtan** [comment]
@mcfrank Yes that would be good—I don't think we had a citation in the original issue.

**Comment by mcfrank** [comment]
Wait sorry, I'm confused... finally got around to looking at this and it
looks like most of these folks have a paper cited in the Contributors page.
Did you want me to write to anyone?

**Comment by alvinwmtan** [comment]
@mcfrank The missing citation is for Eric Walle's dataset

**Comment by mcfrank** [comment]
Walle, E. A.& Campos, J. J. (2014). Infant language development is related to the acquisition of walking. Developmental Psychology, 50, 336-348. 

He, M., Walle, E. A., & Campos, J. J. (2015). A cross-national investigation of the relation between infant walking and language development. Infancy, 20, 283-305. 

Walle, E. A., & Warlaumont, A. S. (2015). Infant locomotion, the language environment, and language development: A home observation study. Proceedings of the 37th Annual Meeting of the Cognitive Science Society, 2577-2582.

**Comment by alvinwmtan** [comment]
@HenryMehta I've directly edited the JSON file. This is from prod, so there might be new datasets from dev that you will need to merge in.
[datasets.json](https://github.com/langcog/wordbank/files/13669474/datasets.json)

**Comment by HenryMehta** [comment]
@alvinwmtan deploying to dev now

**Comment by alvinwmtan** [comment]
@HenryMehta All looks good, except I forgot to propagate "Christina Bergmann, Max Planck Institute for Psycholinguistics" as contributor for all the Dutch datasets. Also, for some reason there are 108 entries for Poulin-Dubois (there should only be 4)—would it be possible to clear out the incorrect ones?

**Comment by HenryMehta** [comment]
@alvinwmtan done
