### ISSUE TITLE
Hoff data only pulls from R01

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#282]
There are two sets of CSVs for the Hoff English–Spanish bilingual dataset (HDPM and R01), but only the R01 dataset appears when pulling data. I'm not sure why this is the case, but if the loading script isn't happy about there being multiple files for the same dataset, it's okay to split the two CSV sets into two datasets (but retain the same dataset_origin_name).

**Comment by HenryMehta** [comment]
@alvinwmtan Are you saying that only R01 data is in the database?

**Comment by alvinwmtan** [comment]
@HenryMehta I think that's the case, yes.

**Comment by HenryMehta** [comment]
@alvinwmtan I've replaced the Hebrew WG citation for the Shalev dataset.  I don't have a WS citation for the Shalev dataset.  Deployed to dev to ensure it is right

**Comment by HenryMehta** [comment]
@alvinwmtan I need some time to think about how to fix this.  Basically the most recently loaded dataset overwrites the previous one because it is saving them on dataset_origin_id (which is allowing comparison across forms and languages but seems to be preventing it within a form).  I have a thought about how to fix but I don't have much time today and I'm away 3 days next week and I don't want to start and then have to remember where I got to, so I would rather leave this for a couple of weeks until I can tackle it in one go

**Comment by HenryMehta** [comment]
I think the above explanation is clearer if you also have the hoff json definition:

```

    {
        "name": "Hoff",
        "dataset": "HDPM",
        "instrument_language": "English (American)",
        "instrument_form": "WS",
        "file": "raw_data/English_American_WS/EnglishWS_Hoff_HDPM.csv",
        "splitcol": false,
        "norming": false,
        "longitudinal": true,
        "contributor": "Hoff, E",
        "license": "CC-BY",
        "citation": "Hoff, E., Core, C., Place, S., Rumiche, R., Señor, M., & Parra, M. (2012). Dual language exposure and early bilingual development. Journal of child language, 39(1), 1-27.",
        "dataset_origin": "Hoff_English_Mexican_Bilingual"
    },
    {
        "name": "Hoff",
        "dataset": "R01",
        "instrument_language": "English (American)",
        "instrument_form": "WS",
        "file": "raw_data/English_American_WS/EnglishWS_Hoff_R01.csv",
        "splitcol": false,
        "norming": false,
        "longitudinal": true,
        "contributor": "Hoff, E",
        "license": "CC-BY",
        "citation": "Hoff, E., Quinn, J. M., & Giguere, D. (2018). What explains the correlation between growth in vocabulary and grammar? New evidence from latent change score analyses of simultaneous bilingual development. Developmental science, 21(2), e12536.",
        "dataset_origin": "Hoff_English_Mexican_Bilingual"
    },
```

**Comment by alvinwmtan** [comment]
@HenryMehta I think option 2 is good!

**Comment by HenryMehta** [comment]
@alvinwmtan I've deployed in dev.  Please take a look and tell me if ok.  If so, I'll implement Friday (I'm away Tuesday - Thrusday)

**Comment by alvinwmtan** [comment]
@HenryMehta I can see the R01 data, and the HDPM dataset appears in `common_datasets` but the data don't seem to appear in `common_administration`? Also, I think reloading didn't flush out the old datasets, so all the datasets/data appear twice.

**Comment by HenryMehta** [comment]
@alvinwmtan  ok - that's a bit of a problem then.  It'll take me longer to sort but I'll try and take a look on Friday

**Comment by mcfrank** [comment]
also note that I just got an email from Erika Hoff:


```
The HDPM subject numbers are published in Hoff et al. 2012:

Hoff, E., Core, C., Place, S., Rumiche, R., Señor, M., & Parra, M. (2012). Dual language exposure and early bilingual development. Journal of child language, 39(1), 1-27.

The R01 subject numbers are published in this:

Hoff, E., Quinn, J. M., & Giguere, D. (2018). What explains the correlation between growth in vocabulary and grammar? New evidence from latent change score analyses of simultaneous bilingual development. Developmental science, 21(2), e12536.
```

**Comment by HenryMehta** [comment]
@alvinwmtan I've had another go at this.  I've had to do it in a new database so when checking please use wordbank2-dev-2 where previously you have wordbank2-dev.
I have resorted to option 1.

If this has worked, can you also check if we have a similar issue with PoulinDubois.  Thanks

**Comment by alvinwmtan** [comment]
@HenryMehta it works now, thanks! What's the name of the new field that you've added—is it `dataset_dataset`? 

I don't think there's an issue with Poulin-Dubois—there aren't datasets with the same instrument and dataset_origin.

**Comment by HenryMehta** [comment]
Good. The new field is dataset_source.  I'll work on getting this to production this evening/tomorrow

**Comment by HenryMehta** [comment]
@alvinwmtan I think I have the data all deployed to production now.  The code changes haven't deployed and I'll look at that tomorrow

**Comment by HenryMehta** [comment]
@alvinwmtan it is now all deployed
