### ISSUE TITLE
Update Russian unilemmas

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#284]
[[Russian_WG].csv](https://github.com/langcog/wordbank/files/9629225/Russian_WG.csv)
[[Russian_WS].csv](https://github.com/langcog/wordbank/files/9629226/Russian_WS.csv)

Some minor updates to the Russian unilemmas (informant recently completed the updating); @HenryMehta it'd be great if you could help to load this

**Comment by HenryMehta** [comment]
@alvinwmtan deployed to dev to test

**Comment by alvinwmtan** [comment]
@HenryMehta I don't seem to see this version in dev? (e.g. item_55 still has uni_lemma "stallion" instead of "horse")

**Comment by HenryMehta** [comment]
@alvinwmtan ok - I'll look again

**Comment by HenryMehta** [comment]
@alvinwmtan sorry about that- I think it is sorted now

**Comment by alvinwmtan** [comment]
@HenryMehta looks good now, thanks!

**Comment by HenryMehta** [comment]
@alvinwmtan live in prod
