### ISSUE TITLE
incoming Korean data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#293]
[korean_cdi_ws.csv](https://github.com/langcog/wordbank/files/11363565/korean_cdi_ws.csv)
[korean_cdi_wg.csv](https://github.com/langcog/wordbank/files/11363566/korean_cdi_wg.csv)
[item_korean_ws.csv](https://github.com/langcog/wordbank/files/11363567/item_korean_ws.csv)
[item_korean_wg.csv](https://github.com/langcog/wordbank/files/11363570/item_korean_wg.csv)

See below for correspondence from Eon-Suk Ko and team:

# message 1

2023년 4월 21일 (금) 오전 1:35, Jun Ho CHAI <[junhoc94@gmail.com](mailto:junhoc94@gmail.com)>님이 작성:
Hello everyone, 

We are excited to share the Korean CDI data collected by our lab members at ChosunBabyLab, Chosun University.

Here, I have attached the CDI data ("korean_cdi_") for word and gesture (WG) and word and sentence (WS) forms, along with the item data ("item_korean_") which summarizes the items used in the WS and WG forms. I have taken great care to clean the data so that it matches the data structure we pulled from Wordbank.

Let me know if you have any suggestions/questions.

Regards,
Jun Ho

# message 2

On Fri, Apr 21, 2023 at 7:22 AM Eon-Suk Ko <[eonsuk@gmail.com](mailto:eonsuk@gmail.com)> wrote:
Jun Ho, thanks for cleaning up the data.

Wordbank Team, our contribution contains data from 482 Korean children, including 222 infants from the WG form covering 8 to 17 month olds, and 260 children from the WS form covering 18 to 36 months. We currently do not have a particular article that we would like to associate with the data set as a whole.

There is a small glitch in the currently submitted data. We will fix it and re-submit it. 

Regards,
Eon-Suk Ko
 

# message 3

Okay, so the glitch is not really a glitch on our part. The item list we provided is based on the existing Korean entries in Wordbank, and the item_642 in the WS list, i.e., "낱말조합여부" translated as "combine" is a section header for grammatical morphemes rather than an actual word. 

Jun Ho and I think it does no harm to leave it as it is. So, we are happy to say the data we provided is ready to be loaded. 

Regards,
Eon-Suk

**Comment by alvinwmtan** [comment]
The data files have some NA issues:
* WG: Items 92, 93, 96 rendered as all NAs in the data (all item-related info is NA except definition and category)
* WS: Items between 637/638, 639/640, 640/641 rendered as all NAs in the data (but no item_ids missing—are these extra items?)

Additionally, I cannot figure out what the encoding format of the input is; it does not appear to be any of: Macintosh, Windows (ANSI), MS-DOS, Unicode (-7, -8, -16), Korean (EUC, Mac, Windows). It would be great if we could get the files in UTF-8 format from the contributors so that we can have the Korean text correctly rendered.

**Comment by alvinwmtan** [comment]
Processed files:
[[Korean_WGComp].csv](https://github.com/langcog/wordbank/files/12456324/Korean_WGComp.csv)
[KoreanWGComp_Chosun_data.csv](https://github.com/langcog/wordbank/files/12456325/KoreanWGComp_Chosun_data.csv)
[KoreanWGComp_Chosun_fields.csv](https://github.com/langcog/wordbank/files/12456326/KoreanWGComp_Chosun_fields.csv)
[KoreanWGComp_Chosun_values.csv](https://github.com/langcog/wordbank/files/12456327/KoreanWGComp_Chosun_values.csv)
[KoreanWS_Chosun_data.csv](https://github.com/langcog/wordbank/files/12456328/KoreanWS_Chosun_data.csv)
[KoreanWS_Chosun_fields.csv](https://github.com/langcog/wordbank/files/12456329/KoreanWS_Chosun_fields.csv)
[KoreanWS_Chosun_values.csv](https://github.com/langcog/wordbank/files/12456330/KoreanWS_Chosun_values.csv)

Note the creation of a new form, Korean WGComp, to accommodate the non-standard comprehension-only WG data. (Policy will also be applied to #252.)

**Comment by HenryMehta** [comment]
@alvinwmtan may I have contributor and citation for both datasets please

**Comment by HenryMehta** [comment]
@alvinwmtan data loaded and deployed to dev

**Comment by alvinwmtan** [comment]
Citation: Jung, J., Chai, J., & Ko, E. (2023, December 8). The Interplay of Family Socioeconomic Status, Parental Engagement, and Maternal Employment on Vocabulary Development in Korean Children. Retrieved from [osf.io/preprints/psyarxiv/depvx](http://osf.io/preprints/psyarxiv/depvx)

Contributor: Eon-Suk Ko, Chosun University

**Comment by alvinwmtan** [comment]
@HenryMehta looks good to me from R
