### ISSUE TITLE
japanese CAT

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#296]
sho tsuji is pulling together the datasets

**Comment by alvinwmtan** [comment]
Data complete; I will upload the formatted data soon

**Comment by alvinwmtan** [comment]
@HenryMehta files ready: 

[[Japanese_WG].csv](https://github.com/langcog/wordbank/files/13832662/Japanese_WG.csv)
[[Japanese_WS].csv](https://github.com/langcog/wordbank/files/13832663/Japanese_WS.csv)
[JapaneseWG_Tsuji_data.csv](https://github.com/langcog/wordbank/files/13832664/JapaneseWG_Tsuji_data.csv)
[JapaneseWG_Tsuji_fields.csv](https://github.com/langcog/wordbank/files/13832665/JapaneseWG_Tsuji_fields.csv)
[JapaneseWG_Tsuji_values.csv](https://github.com/langcog/wordbank/files/13832667/JapaneseWG_Tsuji_values.csv)
[JapaneseWS_Hagihara_data.csv](https://github.com/langcog/wordbank/files/13832668/JapaneseWS_Hagihara_data.csv)
[JapaneseWS_Hagihara_fields.csv](https://github.com/langcog/wordbank/files/13832669/JapaneseWS_Hagihara_fields.csv)
[JapaneseWS_Hagihara_values.csv](https://github.com/langcog/wordbank/files/13832670/JapaneseWS_Hagihara_values.csv)
[JapaneseWS_Minagawa_data.csv](https://github.com/langcog/wordbank/files/13832671/JapaneseWS_Minagawa_data.csv)
[JapaneseWS_Minagawa_fields.csv](https://github.com/langcog/wordbank/files/13832672/JapaneseWS_Minagawa_fields.csv)
[JapaneseWS_Minagawa_values.csv](https://github.com/langcog/wordbank/files/13832673/JapaneseWS_Minagawa_values.csv)
[JapaneseWS_Tsuji_data.csv](https://github.com/langcog/wordbank/files/13832674/JapaneseWS_Tsuji_data.csv)
[JapaneseWS_Tsuji_fields.csv](https://github.com/langcog/wordbank/files/13832675/JapaneseWS_Tsuji_fields.csv)
[JapaneseWS_Tsuji_values.csv](https://github.com/langcog/wordbank/files/13832676/JapaneseWS_Tsuji_values.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan Lines 778-780 in [Japanese_WS].csv and final 3 lines in [Japanese_WG].csv are not valid.  I'm not sure if you just want them deleted.  Please advise

**Comment by alvinwmtan** [comment]
@HenryMehta Yes please, thanks

**Comment by HenryMehta** [comment]
@alvinwmtan For Japanese WG I needed to add categories sounds2, conversations and others to the list of categories in Wordbank.  I set these with a lexical category and class of other.  If you want something different, let me know

**Comment by HenryMehta** [comment]
All deployed to dev

**Comment by alvinwmtan** [comment]
@HenryMehta Great, looks good in dev!

**Comment by alvinwmtan** [comment]
@HenryMehta citation here: 

Hiromichi Hagihara, Monica Barbir, Mikako Ishibashi, Yasuhiro Kanakogi, Masaharu Kato, Irena Lovcevic, Youtao Lu, Yasuyo Minagawa, Yusuke Moriguchi, Masa-aki Sakagami, Yuta Shinya, Hiroki Yamamoto, & Sho Tsuji (2023). A sharable merged dataset on Japanese children’s vocabulary measures using the Japanese MacArthur–Bates Communicative Development Inventory. https://doi.org/10.17605/osf.io/s5ydw

**Comment by HenryMehta** [comment]
@alvinwmtan Is this the citation for all 4 datasets?  And is Sho the contributor for all 4?

**Comment by alvinwmtan** [comment]
@HenryMehta yes this is the citation for all 4 datasets, and I think we can put Sho as the contributor for all 4.
