### ISSUE TITLE
Estonian data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#297]
From Ada Urm: 

```
As it turns out, it took a bit longer to get the datasets ready and checked. So here I have added the Estonian CDI: Words and Sentences dataset (in .csv format). I have included in a separate file the translated scale items according to the current dataset. I also included the ECDI2 form.

 

Since the data is licensed under our university it may not be used for commercial purposes.

 

If our datasets are used the following sources need to be credited:

Urm, A., & Tulviste, T. (2016). Sources of individual variation in Estonian toddlers’ expressive vocabulary. First Language, 36(6), 580-600.

Tulviste, T. (2007). Variation in vocabulary development among Estonian children as a function of child’s gender, birth order, child-care, and parental education. In M Eriksson (Ed.), Proceedings from the First European Network Meeting on the Communicative Development Inventories (pp. 16-21). Gävle, Sweden: University of Gävle.

I am ready to answer any questions regarding the dataset and help out in any way I can.
```

[ECDI2_translated scale items for wordbank.docx](https://github.com/langcog/wordbank/files/11737198/ECDI2_translated.scale.items.for.wordbank.docx)
[ECDI2_Words and Sentences.pdf](https://github.com/langcog/wordbank/files/11737200/ECDI2_Words.and.Sentences.pdf)
[ECDI2_data for wordbank.csv](https://github.com/langcog/wordbank/files/11737202/ECDI2_data.for.wordbank.csv)

**Comment by mcfrank** [comment]
updated data from Ada, now in SPSS format. she has checked this one - don't use the one above. 

[ECDI2_dataset_wordbank_corrected.sav.zip](https://github.com/langcog/wordbank/files/11737676/ECDI2_dataset_wordbank_corrected.sav.zip)

**Comment by alvinwmtan** [comment]
Files ready for import:

[[Estonian_WS].csv](https://github.com/langcog/wordbank/files/11779663/Estonian_WS.csv)
[EstonianWS_Urm_data.csv](https://github.com/langcog/wordbank/files/11779664/EstonianWS_Urm_data.csv)
[EstonianWS_Urm_fields.csv](https://github.com/langcog/wordbank/files/11779665/EstonianWS_Urm_fields.csv)
[EstonianWS_Urm_values.csv](https://github.com/langcog/wordbank/files/11779666/EstonianWS_Urm_values.csv)

**Comment by alvinwmtan** [comment]
@HenryMehta sorry about that, here's the UTF-8 version:
[[Estonian_WS].csv](https://github.com/langcog/wordbank/files/13549099/Estonian_WS.csv)

**Comment by HenryMehta** [comment]
@alvinwmtan 
word tulevik, row 1070 has the value 3 which isn't specified in the values file.  What do you want 3 coded as?

**Comment by alvinwmtan** [comment]
@HenryMehta let's code 3 as NA (error).

**Comment by HenryMehta** [comment]
@alvinwmtan ready to test in dev

**Comment by alvinwmtan** [comment]
@HenryMehta looks good from R, thanks!
