### ISSUE TITLE
German missing/combined words issue

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#301]
> I noticed that four words are missing in the German vocabulary list on wordbank. I think I can guess the reason. They are words which have two meanings. Possibly the way I characterised them in the SPSS file was not appropriate for wordbank. However, they are rather important words, especially the word "das" meaning either "that" or "the", the latter being the neutral gender of the definite article. Both are frequent.
> 
> I noticed that marking with a slash works, as you put Orange/Apfelsine which differentiates the fruit "orange" from the colour "orange". ("Apfelsine" is another German word for the fruit). So, I applied the slash principle and have worked out for the four words how they can - hopefully - be added to the word list. I am attaching this as a word file. The file gives you the line in the SPSS file, the missing word, the text in the SPSS file, and the last column presents my suggestion on how to put the words in the Wordbank list. After the slash you have the German name of the category it is in in the CDI vocabulary list. That should do the trick.

**Comment by mcfrank** [comment]
We fixed the shiny app. 

@alvinwmtan is fixing the database.

This is a more general problem that will require disambiguations to be added to all languages, though.

**Comment by alvinwmtan** [comment]
[[German_WS].csv](https://github.com/langcog/wordbank/files/13385160/German_WS.csv)
New form definition for German, with items disambiguated. Will also fix disambiguation more generally.

**Comment by HenryMehta** [comment]
@alvinwmtan deployed to dev for testing

**Comment by alvinwmtan** [comment]
@HenryMehta Looks good. I'll make a new issue for general disambiguation (which probably won't go into WB2.1, but possibly in WB2.2)
