### ISSUE TITLE
Issue in Norwegian data

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#319]
From Pernille Bonnevie Hansen:

> I'm contacting you as we in the Norwegian CDI team have discovered something in the Norwegian CDI II data in WordBank that we're trying to get to the bottom of. The issue concerns two grammar sections: Word ending nouns and Word ending verbs
> 
> In the WordBank data, the responses for these questions come up as either "" or "Not yet" for all children. But when we go to the form, the questions in these two section concern overgeneralisations. Parents are asked to mark the overgeneralised word forms they have heard from their child. Hence, the only possible answers should be "" (blank) or "Produces" (or something along those lines). Just below is a question about word combinations where "Not yet" is indeed one of the options (along with "Some times" and "Often"). We assumed an error has happened here and that the "Not yet" actually implies "Produces" for the word ending categories. Could you have a look?

**Comment by mikabr** [comment]
I fixed the value mapping via [cf1e3ec](https://github.com/langcog/wordbank/commit/cf1e3ec2ba5b21ef990e673c22329426ca017752). @HenryMehta could you please re-import the Norwegian WS data?

**Comment by HenryMehta** [comment]
@mikabr I have updated the development database (wordbank2-dev-4.canyiscnpddk.us-west-2.rds.amazonaws.com).  Please confirm this has worked before I apply to production

**Comment by mikabr** [comment]
@HenryMehta thanks, just checked, looks good!

**Comment by HenryMehta** [comment]
@mikabr I have loaded to production so closing issue.  Please check it is ok and re-open if required.  Thanks
