### ISSUE TITLE
import catalan data 

### ISSUE THREAD

**Issue by vmarchman** [langcog/wordbank#326]
@HenryMehta @alvinwmtan These data are from the scanning project so we now have item-level data for Catalan.

Two issues:

(1) The WG file does not have any age or sex columns; The WS file has a column for age, but many are missing. No column for sex or any other demographics.  Is the demographic data already in Wordbank?

(2) It is not clear to me whether IDs in the WG are overlapping with the WS form.  The number goes from 1 to ~500 in WG and 1 to ~900 in WS.  I'm assuming these are all different children.

[catalan_wg.xlsx](https://github.com/user-attachments/files/17139110/catalan_wg.xlsx)
[catalan_ws.xlsx](https://github.com/user-attachments/files/17139111/catalan_ws.xlsx)

**Comment by alvinwmtan** [comment]
is this the same data as #240? or a different set of children?

**Comment by vmarchman** [comment]
Right - these are the scans (item-level info) for those data.  So, you already have the summary scores and demographics.

**Comment by alvinwmtan** [comment]
I think we had the item-level data too? That's what was imported

**Comment by vmarchman** [comment]
Ok. I just found it with the scanned data.

**Comment by HenryMehta** [comment]
@vmarchman @alvinwmtan I'm not sure if I am meant to be doing something with this, and if I am, what am I meant to do?

**Comment by vmarchman** [comment]
Sorry @HenryMehta I didn't realize these re-keyed scans were already in Wordbank, so no action needed.
