### ISSUE TITLE
import Ping's Mandarin data

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#43]

**Comment by mikabr** [comment]
Do we want to prioritize this to include in vocab comp?

**Comment by mcfrank** [comment]
Yes if it has good categories we can easily map to part of speech, no otherwise. It will be valuable to know that our findings generalized to other instruments as well as straight CDIs in the long run, but for BUCLD the novelty of BSL is probably more important IMO. 

Mike

**Comment by mikabr** [comment]
TC (toddler checklist) is imported, IC (infant checklist) not yet
