### ISSUE TITLE
set up caching for reports

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#45]
nightly cron job that runs an R script that reads in a bunch of tables and does the queries/joins needed to get the data in a form useful for reports, then writes the results to an R binary file

**Comment by mcfrank** [comment]
FWIW, it's really costly to do the full item by kid merge - currently this results in a 75mb compressed Rdata file that is hard to load. So maybe we should start by caching some smaller versions, e.g. averages across participants or across items. 

Mike
