### ISSUE TITLE
import instrument-specific age limits in db

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#52]
E.g. Norwegian WS goes later in age than english. This may mean we need to have age ranges for instruments encoded in the instruments table. Right now this stuff is hard coded, I believe.

**Comment by mikabr** [comment]
Right now it's hardcoded to be 8:18 for WG and 16:30 for WS, for all languages. What should it be?

**Comment by mcfrank** [comment]
I'm not sure, but I think norwegian goes to 36 months for WS? It's going to depend on the instrument design (and probably on the norming study). We can pull these numbers from the papers though if you can add this to the database...

**Comment by mikabr** [comment]
adding it to the database should be easy

**Comment by mikabr** [comment]
age min and age max values for each instrument are stored in `static/json/instruments.json`
I guessed for some of the values, so not sure they're right, but should be easy to change now
