### ISSUE TITLE
Add Mayor correction

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#54]
Let's implement the Mayor and Plunkett correction for vocab size in the norms and distribution reports. 

http://onlinelibrary.wiley.com/doi/10.1111/j.1467-7687.2010.01024.x/full

We can have it turn on and off via a checkbox?

**Comment by mikabr** [comment]
vocab sizes are computed in a Django/SQL query, which will make this difficult...

**Comment by mcfrank** [comment]
Mika and I spoke a bunch about the mayor correction and are consensus was more or less that it is not possible to do cross linguistically under the current set up, at least not without much more data, but on the other hand there might be versions of the correction that we could implement.
