### ISSUE TITLE
improve smoothing curves in norms report

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#55]
We need to consider what the best smoothing function is for the norms report - not clear right now but the loess is probably not the answer. Quantile regression is good, but we currently don't have the right functional form.

**Comment by mikabr** [comment]
Mike and I mostly implemented this today

**Comment by mcfrank** [comment]
Did a bunch more work on this, think we need package `gcrq` but it's a little rough around the edges. 

Mike

**Comment by mikabr** [comment]
subsumed under #27

**Comment by mikabr** [comment]
gcrq/predictQR have some super weird behavior, e.g.
data with no groups -> predictQR works fine
group data -> predictQR breaks
ungroup data -> predictQR still breaks

**Comment by mikabr** [comment]
Conceptual confusion about gcrq -- predictQR returns a matrix with data points as rows and percentiles as columns. So there is (num percentiles) times too much predicted data (which is, I think, why the demo split curves look all bouncy). Is it supposed to only plot the predicted value for the percentile that the point is actually in? I think there's no possible join to make determining that not crazy hacky...

**Comment by mcfrank** [comment]
FWIW, I had this behavior too in the broken version I checked in. 

Mike

**Comment by mcfrank** [comment]
That's why the insane gather call was nested in the awful code from the original version. You have to gather the predicted values...

Mike

**Comment by mikabr** [comment]
Gather them and then what? Somehow filter to the correct percentile?

**Comment by mcfrank** [comment]
In my code I was generating a percentile by age matrix in wide form then gathering it (not predicting point by point). 

You could predict for an age then select the percentile you want, though that's a little wasteful...

Mike

**Comment by mikabr** [comment]
Oh I see. Predicting for each age rather than each point seems saner, I'll try that.

**Comment by mikabr** [comment]
Fixed the demo split bounciness, things look pretty good now. The curves are still a little less well-behaved than in the old code, I have no idea what's causing that, though.

**Comment by mikabr** [comment]
@mcfrank do you have any idea what could be causing the slightly-odd behavior of the curves? And does it seem like a problem?

**Comment by mcfrank** [comment]
Did you set lambda high in the regression? I was using lambda=60. 

Mike

**Comment by mikabr** [comment]
Yeah, I didn't change the model specification at all.
