### ISSUE TITLE
maintain consistent item-color mappings in item trajectory report

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#57]

**Comment by mikabr** [comment]
This is difficult to do because with the way shiny works, every time inputs like words change, the data is re-computed and a new plot is rendered, with ggplot picking colors for the words based on their alphabetical order. To have consistent color mappings, the app would need to somehow keep track not just of which words were currently selected, but the history of the order in which they were selected, and update this history on word selection changes (which I'm not sure is even possible).

**Comment by mcfrank** [comment]
What about the following:
- set the levels of the factor to the ORDER of the words in the text entry
box
- set a constant color palette with say 10 colors, assigned to each of the
factor levels

So then the first word in the box would always be red, the second would
always be green etc.

Mike

**Comment by mikabr** [comment]
Great point, done.
