### ISSUE TITLE
change stats page age range to 36 months

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#67]

**Comment by mcfrank** [comment]
not updated on prod? 

Mike

**Comment by mikabr** [comment]
SSH isn't working on airplane wifi, I'll pull when I land (or you can pull
:))

**Comment by mcfrank** [comment]
Haha. I was wondering about that. We haven't taken off yet. Try vpn and then ssh. 

Mike

**Comment by mikabr** [comment]
up now
