### ISSUE TITLE
import CLEX data

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#70]
@mcfrank @dyurovsky (just tagging you guys to make sure you know this is where the action's at)

**Comment by mikabr** [comment]
Resolved all the horrible unicode issues. That should incidentally help #53, when we get there.

**Comment by mikabr** [comment]
What's going on here: import_clex is an R script that reads in data from the cdiclex mysql database and puts in a form that's more-or-less ready for our existing import code. For each dataset that it's told to export, it creates a directory and 4 csv files: the instrument definition, the dataset field mapping, the dataset value mapping, and the actual dataset data. There are a couple of things in the gap between this output and what we need for data import. Going to describe each in a separate comment.

**Comment by mikabr** [comment]
Excel vs CSV : Right now our data import expects the data and mapping info to be sheets of a single excel file. Writing excel files from R takes approximately infinite time, while writing CSVs takes approximately zero time, so import_clex writes 3 separate CSVs instead. From there, we can either 1) manually/programmatically combine them into an excel file, or 2) change the data import code to handle separate CSVs. 1 is a lot easier, but 2 has the advantage of also moving us away from relying on excel, which is desirable anyway.

**Comment by mikabr** [comment]
Sentences/Gesture data: the clex db seems to be lacking some info to get the sentences/gestures data sorted out, in that there doesn't seem to be a value mapping anywhere (like cdi_vocabulary_config for words). There's also not a straightforward way to get from CLEX's category names to our category names. Possibly manual spreadsheet fiddling is the answer to both of these issues.

**Comment by mikabr** [comment]
Item info: CLEX has glosses, but we need to get additional item information from somewhere (lexical category, complexity category). Probably more manual spreadsheet fiddling.

**Comment by mikabr** [comment]
I think that's the set of obstacles, though I'm sure other minor things will come up :P

**Comment by mikabr** [comment]
Bad news... I just checked, and the set of languages in CLEX that have sentences data is exactly the set that's already in wordbank. So we're going to have a fair number of new vocabulary data, but no new grammar data =\

**Comment by mcfrank** [comment]
Oh no. Shall I write to Rune to ask him if any of the other languages had sentences data? 

Mike

**Comment by mcfrank** [comment]
I think CSVs are definitely the way to go for the future. 

Mike

**Comment by mikabr** [comment]
Alright, all of the data import code now supports both excel and csv, and most of the CLEX datasets are importable. There's an issue with the value mapping in a few of the datasets, in that they have values that I have no idea how to interpret...
Croatian WS: 0, 1, 2, 3
Turkish WG: 0, 1, 2, 3, 9
Turkish WS: 0, 1, 2, 9
All of the CLEX datasets also don't have lexical category coded yet.

**Comment by mikabr** [comment]
Asking Rune if he has any more grammar data lying around seems like a good idea.

**Comment by mikabr** [comment]
[So many languages](https://github.com/langcog/wordbank/blob/clex/Ranalysis/usingWordbank/usingWordbank.html)! :D

**Comment by mikabr** [comment]
All of the shiny apps work with the new data!

**Comment by mcfrank** [comment]
Awesome!

Mike
