### ISSUE TITLE
import British Sign Language data

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#71]

**Comment by mikabr** [comment]
Do we want to prioritize this to include in vocab comp?

**Comment by mcfrank** [comment]
I think so--it's very novel afaik to look at vocab comp in a manual language. 

Mike

**Comment by mikabr** [comment]
Hmm, I'm worried about getting BSL to work for this, because
- it's a comprehension/production WG-style form (we're currently doing everything on WS production, but could try WG comprehension?)
- there's a total of 161 administrations over ages 8 to 36, so it's going to be sparse

**Comment by mcfrank** [comment]
I see... the sparsity is unavoidable - it may not be meaningful, but I'd guess we still get something.

But the WG issue does suggest that we should at a minimum check for these biases in the comprehension and production data on WG. How hard is that? 

Mike

**Comment by mikabr** [comment]
BSL is imported and on prod.
[Vocab comp] (https://rawgit.com/mikabr/vocab-comp/master/vocab_comp.html) now has WG analyses.

**Comment by mcfrank** [comment]
Great! 

BSL -> "British Sign Language" :) 

More about new vocab comp in another thread. 

Mike

**Comment by mikabr** [comment]
Yeah, the reason it's BSL is that there are bits of code in various places
that expect languages to not have spaces in them... should probably fix
that, though

**Comment by mcfrank** [comment]
Errors on the space in name issue, broken on prod:

Joining by: "momed_id"
Joining by: "instrument_id"
Auto-disconnecting mysql connection (0, 0)
Joining by: "child_id"
Joining by: "instrument_id"
Joining by: "category_id"
Error in .local(conn, statement, ...) : 
  could not run statement: Table 'wordbank.instruments_british sign language_wg' doesn't exist

**Comment by mikabr** [comment]
That just needs a pull, data_loading itself is fixed.
