### ISSUE TITLE
load table connections on demand in shiny apps

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#74]
A lot of the latency in loading a shiny app is in running get.instrument.tables, because it connects to every instrument's table and that takes a while. We can improve shiny app load time by only connecting to a table when its instrument is needed.

**Comment by mikabr** [comment]
I realized that norms and hists don't actually need to run get.instrument.tables at all, since the data they use is all in administrations. So I made them not to do it, and they're significantly faster. The item trajectories app would still benefit from this optimization, though.

**Comment by mcfrank** [comment]
nice!

Mike
