### ISSUE TITLE
create contributors page

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#80]
It's becoming urgent that we attribute and cite data appropriately, I think. My proposal is to replace the "contribute link" with a "contributors" link that has the contributions form linked from there. 

Do we want to allow people to access by dataset anywhere in the reports codebase?

**Comment by mikabr** [comment]
What information should be on this page for attribution/citation? Right now we have a source table that's intended to recorded per-dataset info, but it just has name (e.g. Marchman), dataset (e.g. Norming), language, and form. We can add arbitrary additional information to it.

**Comment by mcfrank** [comment]
We want to add a list of contributor labs (linked to lab pages), along with the citations for particular datasets. I was imagining a table with language on the left, and a list of contributors/citations, e.g.

English	Fenson et al., 2007.. blah blah, Manual.  (N=XYZ)
		Linda Smith Lab (N=XYZ)
Turkish 	Kuntay et al. blah blah, Journal of Child Language

What do you think of that?

**Comment by mikabr** [comment]
That seems right. What I meant was that this page can be automagically made in Django from the source table, it just needs whatever additional information we want -- a citation for datasets that were presented in a paper and a lab otherwise?

**Comment by mcfrank** [comment]
> That seems right. What I meant was that this page can be automagically made in Django from the source table, it just needs whatever additional information we want -- a citation for datasets that were presented in a paper and a lab otherwise?

Exactly. Sounds great - and making it automatically is a very good idea. 

Mike

**Comment by mikabr** [comment]
Draft of this is up on dev
http://54.149.39.46/contributors
Needs actual citations instead of just names, but does it otherwise look like a good structure?

**Comment by mcfrank** [comment]
Yes, that looks great! I think we probably want to have form next to N? (e.g. WS/WG)? Otherwise it looks odd to have two different contributions to the same language?

Mike

**Comment by mcfrank** [comment]
Oh and, we probably want the "to contribute" bit in the same text block at the top!

Mike

**Comment by mikabr** [comment]
Moved the contribute text up, added WS/WG labels, put in something approximating citations.

**Comment by mcfrank** [comment]
Gorgeous. 

Let's let Virginia say what she would like the affil to be on the Dallas/Wisconsin datasets. (Maybe just current Stanford affil makes sense?)

Mike

**Comment by mikabr** [comment]
Now ready to ship, I think?

**Comment by mcfrank** [comment]
Yup!

And wordbank-contact@stanford.edu works well. 

best, 

Mike

**Comment by vmarchman** [comment]
Contributors page looks great.  Did we substitute a simple email for the
Contributors form?  Seems like that form required people to provide lots of
useful information, no?

On Fri, Apr 24, 2015 at 12:04 PM, Michael Frank <notifications@github.com>
wrote:

> Yup!
>
> And wordbank-contact@stanford.edu works well.
>
> best,
>
> Mike
>
> > On Apr 24, 2015, at 12:00 PM, Mika Braginsky <notifications@github.com>
> wrote:
> >
> > Now ready to ship, I think?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/langcog/wordbank/issues/80#issuecomment-96037206>.
>



-- 

*********************************
Virginia A. Marchman, Ph.D.
marchman@stanford.edu
Research Associate
Center for Infant Studies
Psychology
Stanford University
Stanford, CA  94305
650-723-1257
*********************************

**Comment by vmarchman** [comment]
Contributors page looks great.  Did we substitute a simple email for the
Contributors form?  Seems like that form required people to provide lots of
useful information, no?

**Comment by mcfrank** [comment]
We did - on the theory that we needed to have extensive exchanges with people anyway, and that the flow of email/data wouldn't be too bad going forward. But we can revisit if it gets hectic. 

Mike
