### ISSUE TITLE
norms/dists apps faceting/grouping behavior

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#81]
I was playing with the demographic variables and realized that it's really hard to make quantitative comparisons across demographics the way we've done it. 

I propose we:
* change the split variable to the color
* change the facet variable to the quantile 
* add a "100%" quantile setting that just shows the median, and relabel these to say "median", "tertiles (33%)", "quartiles (25%)" , "quintiles (20%)" , "deciles (10%)"

**Comment by mcfrank** [comment]
Feedback from meeting 4/29:
* quantiles are cutpoints, not middles
* dot coloring is by quantile range (so we need to cut ranges and use gcrq to color)
* facet behavior

**Comment by mikabr** [comment]
[http://54.149.39.46:3838/norms_app/](New version of norms app) has the faceting and coloring behavior we discussed, doesn't color points, treats quantiles as cutpoints with a c(0.1, 0.25, 0.5, 0.75, 0.9) option, and uses a (much better) custom color palette.

**Comment by mikabr** [comment]
Still need to do the demo clumping fix.

**Comment by mcfrank** [comment]
looks great!

Mike

**Comment by mcfrank** [comment]
Is it time to switch to geom_dl(method="last.qp") for the labels of the quartiles? might look better...

Mike

**Comment by mcfrank** [comment]
Also, a few more comments:

- for facets, the order of birth orders is correct, but for medians somehow it's wrong
- for english ethnicity, the app chokes and just prints "sample sizes:" - same for hebrew momed.

Mike

**Comment by mikabr** [comment]
Using direct labels sounds like a good idea (and that makes the order being wrong in the legend a moot point).
Those cases of the app failing is gcrq declaring it has a "singular design" and I'm not sure what its problem is... possibly the demo group clumping will help?

**Comment by mcfrank** [comment]
@dyurovsky will investigate fitting taus for the middles between percentiles, then using those to color points appropriately.

**Comment by mcfrank** [comment]
if we can't do this by fall sprint, we close the issue.

**Comment by mikabr** [comment]
Are we giving up on this?

**Comment by mcfrank** [comment]
we're fine with un-colored points.
