### ISSUE TITLE
Stitch words between forms

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#85]
It would be neat to consider an extension to the item report that stitches items between forms - basically, fits a single growth model with intercepts for instruments to all the data for a word, provided that it appears on both instruments.

**Comment by mcfrank** [comment]
So here are some PNGS that just glue together random words from WS to WG in English and Spanish. It looks really good...

I think this is a nice argument for adding the "both" instrument to the Items report. 

![ws to wg spanish](https://cloud.githubusercontent.com/assets/1158807/7530087/61c738c6-f4f7-11e4-8cba-ecd80dcd087f.png)
![ws to wg](https://cloud.githubusercontent.com/assets/1158807/7530088/61c73b1e-f4f7-11e4-8955-645fe83bb249.png)

**Comment by vmarchman** [comment]
that looks awesome.

On Thu, May 7, 2015 at 8:27 PM, Michael Frank <notifications@github.com>
wrote:

> So here are some PNGS that just glue together random words from WS to WG
> in English and Spanish. It looks really good...
>
> I think this is a nice argument for adding the "both" instrument to the
> Items report.
>
> [image: ws to wg spanish]
> <https://cloud.githubusercontent.com/assets/1158807/7530087/61c738c6-f4f7-11e4-8cba-ecd80dcd087f.png>
> [image: ws to wg]
> <https://cloud.githubusercontent.com/assets/1158807/7530088/61c73b1e-f4f7-11e4-8955-645fe83bb249.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/langcog/wordbank/issues/85#issuecomment-100088608>.
>



-- 

*********************************
Virginia A. Marchman, Ph.D.
marchman@stanford.edu
Research Associate
Center for Infant Studies
Psychology
Stanford University
Stanford, CA  94305
650-723-1257
*********************************
