### ISSUE TITLE
Is it possible to download the fitted values?

### ISSUE THREAD

**Issue by vmarchman** [langcog/wordbank#95]
I was expecting the actual fitted values generated by the curve-fitting procedure to be provided in the download.  Right now, it's raw data labeled by the split variable, but that doesn't help me compare the fitted estimates.  Is it possible to compare the, e.g., 50th percentile (fitted) value for 24-mos boys vs. girls, without having to simply eye-ball the plot?

**Comment by mikabr** [comment]
We have the data points and fitted curves in separate data frames, with the download button giving you the data points. We could add another download button that gives you the fitted curves.

**Comment by mikabr** [comment]
temporary fit value downloading is implemented, better presentation is going to happen in #97
