### ISSUE TITLE
add human-readable fitted value tables to apps

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#97]

**Comment by mikabr** [comment]
Made a first pass at this, it's [up on dev](http://54.149.39.46:3838/vocab_norms/). Doing age as the columns makes it really wide, so right now it has quantiles as columns instead. Is that okay, or undesirable? Also it's tricky to render a bunch of separate tables for different demo groups, so right now it has them all in one table, is that okay or bad?

**Comment by vmarchman** [comment]
This is great and very human-readable.  Thanks!  One table is fine.  Demo
label column is redundant, no?  Can we add language, form and measure
(e.g., produces) columns?

On Wed, May 27, 2015 at 11:57 PM, Mika Braginsky <notifications@github.com>
wrote:

> Made a first pass at this, it's up on dev
> <http://54.149.39.46:3838/vocab_norms/>. Doing age as the columns makes
> it really wide, so right now it has quantiles as columns instead. Is that
> okay, or undesirable? Also it's tricky to render a bunch of separate tables
> for different demo groups, so right now it has them all in one table, is
> that okay or bad?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/langcog/wordbank/issues/97#issuecomment-106201072>.
>



-- 

*********************************
Virginia A. Marchman, Ph.D.
marchman@stanford.edu
Research Associate
Center for Infant Studies
Psychology
Stanford University
Stanford, CA  94305
650-723-1257
*********************************

**Comment by mcfrank** [comment]
Agreed - this looks great to me. A few comments:

* Could round to one decimal in the table. 
* I see why we'd want those columns (language, form, measure), but I think they will decrease the readability of the table online. Maybe we should add them when you download? 
* can we change the download links to "download plot", "download table", and "download raw data"?
* Can we change the details box below to be grey?

Thanks!
