### ISSUE TITLE
redesign landing page

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#99]
![img_5773](https://cloud.githubusercontent.com/assets/1158807/7920212/51832d12-0852-11e5-8d68-818f4065015e.jpg)

Basically, want to promote good content onto landing page. Two interactive reports, language bar graph from stats page, other buttons.

**Comment by mikabr** [comment]
[Home page redesign](http://54.149.39.46/) is up. Comments?

**Comment by vmarchman** [comment]
Looks great!  I love the bubbles showing the number of administrations.  I
guess the smallest is British Sign language? It's a bit hard to read though.

Can Bears co-exist with Walruses?

On Mon, Jun 8, 2015 at 1:25 PM, Mika Braginsky <notifications@github.com>
wrote:

> Home page redesign <http://54.149.39.46/> is up. Comments?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/langcog/wordbank/issues/99#issuecomment-110126953>.
>



-- 

*********************************
Virginia A. Marchman, Ph.D.
marchman@stanford.edu
Research Associate
Center for Infant Studies
Psychology
Stanford University
Stanford, CA  94305
650-723-1257
*********************************

**Comment by mikabr** [comment]
I'd like to propose some more design changes (only tangentially related to the original issue, but this seems like a reasonable place for it). They are
- integrating a streamlined version of the about page into the [homepage](http://54.149.39.46/)
- adding "meet the team" thumbnails to the [homepage](http://54.149.39.46/)
- pulling in posts for the [blog](http://54.149.39.46/blog) through the blogger API, to have custom and consistent styling and avoid iframe scrolling issues
- adding some [blog](http://54.149.39.46/blog) sidebar content: upcoming events and resource links #69 
How's it look?

**Comment by vmarchman** [comment]
Looks great!

**Comment by mcfrank** [comment]
Agreed! The mobile rendering of the homepage looks a little odd (the pictures are all different scales etc.) but desktop looks excellent. I think it’s a very good idea to prune away the about page.

Mike
